### ISSUE TITLE
Preferred Source for Understanding Apache Config Files

### ISSUE THREAD

**Issue by chuckac** [susanBuck/e2-fall20#10]
Hi!  As a general resource, would anyone have a recommended source you like to use to learn more about Apache config files?

**Comment by susanBuck** [comment]
The official docs for Apache config files can be found here: 
http://httpd.apache.org/docs/2.4/configuring.html

It's thorough - as you would expect from official docs - but doesn't go out of its way to be beginner friendly. 

Later today/tomorrow, I'll put together a run through of the Apache configs we're using and share it with everyone.

If any other classmates has a go-to resource they've found/liked for Apache stuff, would love to hear about it!

**Comment by susanBuck** [comment]
Update: I finished the above referenced notes and I'll introduce them in this week's upcoming videos. : )
