### ISSUE TITLE
Issue with Results view

### ISSUE THREAD

**Issue by mborjon** [susanBuck/e2-fall20#101]
Hello @susanBuck,

For P3, I getting an error when I display my results on e2p3 index page.  Any suggestions?  Am I accounting for the 'tie' option the correct way? Or do you see any other issues?

**error message:**
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) in /Applications/XAMPP/xamppfiles/htdocs/e2/p3/cache/426a226c4b00d5c408ccfccfb34046c072d7b2d9.php:48 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/e2/p3/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/Applications/X...', Array) #1 /Applications/XAMPP/xamppfiles/htdocs/e2/p3/vendor/illuminate/view/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/Applications/X...', Array) #2 /Applications/XAMPP/xamppfiles/htdocs/e2/p3/vendor/illuminate/view/View.php(125): Illuminate\View\View->getContents() #3 /Applications/XAMPP/xamppfiles/htdocs/e2/p3/vendor/illuminate/view/View.php(90): Illuminate\View\View->renderContents() #4 /Applications/XAMPP/xamppfiles/htdocs/e2/p3/vendor/susanbuck/e2core/src/App.php(289): Illuminate\View\View->render() #5 /Applications/XAMPP/xamppfiles/htdocs/e2 in /Applications/XAMPP/xamppfiles/htdocs/e2/p3/cache/426a226c4b00d5c408ccfccfb34046c072d7b2d9.php on line 48

**Here is the error page in cache:**
<img width="1350" alt="Screen Shot 2020-12-06 at 3 15 29 PM" src="https://user-images.githubusercontent.com/38201146/101296003-e2f1ef00-37d5-11eb-80b5-5f4974084ad5.png">

**Here is the index.blade.php page:**
<img width="1323" alt="Screen Shot 2020-12-06 at 3 16 36 PM" src="https://user-images.githubusercontent.com/38201146/101296034-0a48bc00-37d6-11eb-912e-e0293bb0cfb9.png">

**Here is my AppController page:**
<img width="1101" alt="Screen Shot 2020-12-06 at 3 17 29 PM" src="https://user-images.githubusercontent.com/38201146/101296054-2a787b00-37d6-11eb-96e0-1df09c170314.png">

**Here is the index view file from my p2 project that I attempted to translate into blade:**
<img width="766" alt="Screen Shot 2020-12-06 at 3 18 15 PM" src="https://user-images.githubusercontent.com/38201146/101296076-45e38600-37d6-11eb-9894-285abdc5232d.png">

Thanks,
Melinda

**Comment by chuckac** [comment]
@mborjon I believe you need a second @endif on your index.blade.php file.  You've opened two @if statements (results and results conditions) so you need to close them both.

**Comment by susanBuck** [comment]
Confirming @chuckac's suggestion. Let us know if that doesn't sort things out.

**Comment by mborjon** [comment]
@susanBuck and @chuckac, thank you so much!  That seems to work to get the results to display.  But now, I am getting an error (only) when I do not make a choice (do not check a radial button), which I set to require for this game.  

Errrors:
Notice: Trying to access array offset on value of type null in /Applications/XAMPP/xamppfiles/htdocs/e2/p3/cache/426a226c4b00d5c408ccfccfb34046c072d7b2d9.php on line 48

Notice: Trying to access array offset on value of type null in /Applications/XAMPP/xamppfiles/htdocs/e2/p3/cache/426a226c4b00d5c408ccfccfb34046c072d7b2d9.php on line 51
Sorry, you lost, please try again.

**Screen with error**
<img width="1111" alt="Screen Shot 2020-12-07 at 12 31 08 PM" src="https://user-images.githubusercontent.com/38201146/101402105-2b69e500-3888-11eb-8406-dc44a7fb9cd8.png">

**The 426xx cache page referenced in error**
<img width="1233" alt="Screen Shot 2020-12-07 at 12 26 19 PM" src="https://user-images.githubusercontent.com/38201146/101402223-55bba280-3888-11eb-85db-d3b233816492.png">

**The index.blade.php page**
<img width="1177" alt="Screen Shot 2020-12-07 at 12 33 52 PM" src="https://user-images.githubusercontent.com/38201146/101402332-784dbb80-3888-11eb-8fcd-c04e4c2b02a0.png">

**The app controller with game logic**
<img width="921" alt="Screen Shot 2020-12-07 at 12 34 34 PM" src="https://user-images.githubusercontent.com/38201146/101402402-91ef0300-3888-11eb-840e-414b6a049e32.png">

**Comment by susanBuck** [comment]
@mborjon - Can you push your latest changes to github so I can clone your project locally for debugging?

**Comment by mborjon** [comment]
@susanBuck Done. Here is the link to my p3 on GitHub: https://github.com/mborjon/e2/tree/master/p3

Thanks!

**Comment by susanBuck** [comment]
Thanks! Cloning now - will follow-up shortly.

**Comment by susanBuck** [comment]
The error is coming from this code:

```php
@if($results)
    <p>You chose: {{ $results['choice']}}</p>
@endif

@if($results['Tie'])
    It’s a tie.
@elseif($results['winner'])
    Congratulations, you won!
@else
    Sorry, you lost, please try again.
@endif
```

In the above code you correctly wrapped the line `<p>You chose: {{ $results['choice']}}</p>` in an _if_ block that first checks that `$results` exists. If you didn't do this, you would have an error when it tried to access `$results['choice']`.

The problem, is the rest of the code (displaying _"Its a tie"_, or _"Congratulations..."_, or _"Sorry..."_ ) **also need to be wrapped in the if block that first checks that $results exists** because all of that code is also dependent on `$results` existing.

To address this, your code should look more like this:

```php
@if($results)

    <p>You chose: {{ $results['choice']}}</p>

    @if($results['Tie'])
        It’s a tie.
    @elseif($results['winner'])
        Congratulations, you won!
    @else
        Sorry, you lost, please try again.
    @endif

@endif
```

**Comment by mborjon** [comment]
@susanBuck Thank you!  It's working now. :)
