### ISSUE TITLE
Undefined Variable Warning from Cache PHP file

### ISSUE THREAD

**Issue by chuckac** [susanBuck/e2-fall20#102]
Hey All -- 

I'm running into an undefined variable ($battle) that's originating from a cache file (seemingly).  I've deleted/cleared the cache files, but somehow, the warning persists (second screenshot).  Any thoughts on a fix?  

The first screenshot is the relevant AppController code declaring/passing the $battle variable. I left dump($battle) in the code, which corresponds to the browser view. The data is correct/matches my 'battles' database records. 

AppController Code

![code_snip](https://user-images.githubusercontent.com/29901852/101300122-878a2600-3802-11eb-9e68-d693ab37eeda.PNG)

Browser Warnings

![battle details output](https://user-images.githubusercontent.com/29901852/101300130-91ac2480-3802-11eb-9054-a7117754950e.PNG)

**Comment by maqboolk** [comment]
@chuckac 

What is the name of your blade file? 
 what if you change the **battles** to **battle** (singular) on line 38?

**Comment by susanBuck** [comment]
Confirming @maqboolk's suggestion.

Also, here's a post that has details on how to track down errors when they occur in view cache files:

[**Quick tip: Debugging Views**](https://github.com/susanBuck/e2-fall20/issues/94)

**Comment by susanBuck** [comment]
Circling back to this post to give it a closer look..

It looks like you're not passing any data to your view.

```php
return $this->app->view('battles');
```

As a result, when you try to access `$battle` in the view, it's throwing an error - nothing is making that variable available in the view.

Assuming you want to do something like this:

```php
return $this->app->view('battles', ['battle' => $battle]);
```

Ref: https://hesweb.dev/e2/notes/php/e2framework/views#view-data

(If you have follow-up questions about this, please update your Github repository with the latest code so I can see things exactly as you see it on your end)

**Comment by britney-sandau** [comment]
I too was getting a similar error when I was following along with the lecture videos. On video 2 around the 25 min mark. Would it have something to do with the "sudo chmod 777 cache" command being entered for the wrong folder. I believe I entered it for my e2 folder at first and then added the command to my p3 folder.

![image](https://user-images.githubusercontent.com/57762932/101682455-a3274380-3a31-11eb-8a4a-e21a185eb2e1.png)

**Comment by britney-sandau** [comment]
I just noticed that my error was error was due to a spelling error. Maybe that might case.

**Comment by chuckac** [comment]
Thanks all for the advice.  

@susanBuck  it was a passing the data issue.  Your suggestion solved it.  Thanks!

**Comment by susanBuck** [comment]
@chuckac Glad to hear it!
