### ISSUE TITLE
P3 - Undefined Variable

### ISSUE THREAD

**Issue by trnason** [susanBuck/e2-fall20#104]
Good Morning,

Trying to add this bit of code to my round.blade.php file

<p>The computer choose {{$results['computerchoice']}}</p>

but I keep getting an undefined variable error. In my index.blade.php file it works fine which is why I am a bit confused. This bit of code just outputs what the computer choose on the Rock Paper Scissor game.  

<img width="1278" alt="Screen Shot 2020-12-07 at 8 02 45 AM" src="https://user-images.githubusercontent.com/52473207/101360320-1af34380-3863-11eb-8611-65efe1e13da6.png">

Git Hub: https://github.com/trnason/e2/tree/master/p3/views

**Comment by susanBuck** [comment]
Hi @trnason - Cloning your code locally now to test/debug. Will follow-up shortly.

**Comment by susanBuck** [comment]
@trnason - Is your repo up to date? I see the last commit was 4 days ago, and in the version I see now there is no error/no reference to _$results_ in *round.blade.php*

**Comment by trnason** [comment]
Hi Professor, 

Thanks for looking into this! I published it to prod without that one line of code in the round.blade.php file. Do you need me to publish it in prod with that line of code in it? It will obviously contain the error but if that will help figure out the issue I certainly can!

**Comment by susanBuck** [comment]
The problem I see is there is no `$results` variable made available to the `round.blade.php` view:

Here's the method that returns that view:
```php
 public function round()
    {
        $id = $this->app->param('id');
        
        $round = $this->app->db()->findByID('rounds', $id);
        
        return $this->app->view('round', [

        'round' => $round

        ]);
    }
```

This code defines a **round** variable and passes it to the view, but no **results**...

Perhaps you meant your line to be:

```html
The computer choose {{$round['computerchoice']}}
```

?

**Comment by trnason** [comment]
Hi Professor,

Thanks for looking into this. The code "The computer choose {{$results['computerchoice']}}" is the right code I need since it is working fine in the index.blade.php file.

Yes, it looks like $results has not been made available to the round.blade.php view. The problem is that I already have a method for round and when I try to make another one to include $results I get an error saying that I can't have another one. Is there a way to add $results in the existing round method since I need both $rounds and $results? I have tried putting it inside the curly brackets but to not avail. 

```php
 public function round()
    {
        $id = $this->app->param('id');
        
        $round = $this->app->db()->findByID('rounds', $id);
        
        return $this->app->view('round', [

        'round' => $round


        ]);
    }
```

This is the method that index.blade.php is referencing and it can get the $results variable so I thought I would just be able to copy this inside the round method but it gives me an error. 

```php
    public function index()
    {
        $results = $this->app->old('results');
        
        return $this->app->view('index', [
          'results' => $results


        ]);
    }
```

**Comment by susanBuck** [comment]
Hi @trnason - Can you please push your latest changes to Github? I understand there might only be small changes but I need to be able to work with your code on my machine *exactly* as you're seeing it in order to best assist you.

Three commands to push all your changes:
```
git add --all
git commit -m "Latest changes"
git push
```

**Comment by trnason** [comment]
Sure thing. Done!

**Comment by susanBuck** [comment]
Thank you! Cloning locally now to run it on my machine and look at the full picture.

**Comment by susanBuck** [comment]
Hi @trnason -

I made a video walking through your code explaining what is going on - [you can view it here](https://www.youtube.com/embed/v0EN3alTtcw?rel=0&showinfo=0).

(FYI as of this posting the video is still processing, so if it doesn't load right away, give it a few minutes)

**Comment by trnason** [comment]
Thank you so much!
