### ISSUE TITLE
Initializing variables at the start of a session

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#106]
I would like to initialize a variable and an array at the start of a session.

```
$haveResults = false;
$board = array(
  "1"=>"1", "2"=>"2", "3"=>"3",
   "4"=>"4", "5"=>"5", "6"=>"6",
    "7"=>"7", "8"=>"8", "9"=>"9"
);
```

I would also like to reinitialize them at the start of a new game.

I can do this with an **Initialize** button, but anyway to trigger it automatically in the e2Framework?

:-)

**Comment by susanBuck** [comment]
What about placing that code in the start of the Controller method that is being triggered by the page you're loading?

e.g.:
```php
<?php
namespace App\Controllers;

class AppController extends Controller
{
    /**
     *
     */
    public function index()
    {
        $haveResults = false;
        $board = array(
        "1"=>"1", "2"=>"2", "3"=>"3",
        "4"=>"4", "5"=>"5", "6"=>"6",
        "7"=>"7", "8"=>"8", "9"=>"9"
    );

        return $this->app->view('index', [
        'haveResults' => $haveResults,
        'board' => $board,
    ]);
    }
}
```

**Comment by CrimsonSIS** [comment]
Is there _e2Framework_ functionality comparable to

**session_start();
isset();**

to initialize variables?

Are we allowed to use session logic?

I'll be altering them subsequently. Re-invoking the index Controller method would reset them to initial values, otherwise...

**Comment by susanBuck** [comment]
Oh sorry, didn't see _session_ mentioned in the post, and missed it in the subject. : )

See: 
https://hesweb.dev/e2/notes/php/e2framework/app#sessionset
https://hesweb.dev/e2/notes/php/e2framework/app#sessionget

(Note: No need to invoke session_start when using these methods; it's done for you)

**Comment by susanBuck** [comment]
Follow-up: You did mention session in the post. Not sure how I missed that! : )

**Comment by CrimsonSIS** [comment]
Simultaneous brain hiccup...

:-)

**Comment by CrimsonSIS** [comment]
Reading the documentation for that now...

**Comment by susanBuck** [comment]
Did you managed to get done what you were looking to do @CrimsonSIS ?  Let me know if you have any follow-up q's or if I can close this thread. : )

**Comment by CrimsonSIS** [comment]
Ok from my perspective. :-)
