### ISSUE TITLE
404 Error when Setting up Routes 

### ISSUE THREAD

**Issue by walshkelsey** [susanBuck/e2-fall20#108]
I'm getting a 404 error when testing my routes and I cannot figure out what I'm doing wrong. My code is not showing any errors in VSCode and I've cleared my cache and cookies on my browser in case that was the issue. Any idea what might be happening? 

App Controller Code:

```
<?php
namespace App\Controllers;

class AppController extends Controller
{
    public function index()
    {
        return $this->app->view('index', [
        ]);
    }
    
    public function history()
    {
        return 'This is the history page';
    }

    public function round()
    {
        return 'This is the round page';
    }
}
```

Route code:

```
<?php

# Define the routes of your application

return [
    # Ex: The path `/` will trigger the `index` method within the `AppController`
    '/' => ['AppController', 'index'],
    '/history' => ['AppController', 'history'],
    '/round' => ['AppController', 'round'],
];
```

**Comment by susanBuck** [comment]
@walshkelsey -

A few questions to help you debug this:

+ Does this happen with all routes, including `/` ?
+ Is this specific to your local server, production server, or both?
+ Can you share a screenshot of the error in your browser (including the URL bar)?

**Comment by walshkelsey** [comment]
> @walshkelsey -
> 
> A few questions to help you debug this:
> 
> * Does this happen with all routes, including `/` ?
> * Is this specific to your local server, production server, or both?
> * Can you share a screenshot of the error in your browser (including the URL bar)?

Hi @susanBuck, after leaving it alone for the night, it does seem to be working now. I'm not sure what happened there...

To answer your questions:

No, e2p3.loc/ works fine. 

This is to my local server only; I have not yet deployed to production. 

Since it now magically works, I can't recreate the issue to get the error, though it was the traditional 404 page not found with a link back to e2p3.loc/

**Comment by susanBuck** [comment]
Huh, well - glad it sorted itself out!  : ) Let me know if the problem pops up again.
