### ISSUE TITLE
Getting "chown: invalid user: ‘www-data’" when deploying framework to production

### ISSUE THREAD

**Issue by pranjal-joshi97** [susanBuck/e2-fall20#109]
Hi all, 
I'm getting this error when following the [Permissions ](https://hesweb.dev/e2/notes/php/frameworks/deploy#permissions)step to deploy my p3 to production:
![image](https://user-images.githubusercontent.com/42822597/101470784-086b2e00-3979-11eb-8d58-3948eff6c3b9.png)
Is this happening because I'm running XAMPP Apache as an admin?

Thanks in advance!

**Comment by susanBuck** [comment]
Hi @pranjal-joshi97 -

It looks like you're running that command on your computer (`c:\xampp\htdocs\e2\p3`). 

It should be run on the production server within the directory `/var/www/html/e2/p3`.

**Comment by pranjal-joshi97** [comment]
Got it! That worked haha thank you!
