### ISSUE TITLE
elevante nano c:\Windows\System32\drivers\etc\hosts is not working

### ISSUE THREAD

**Issue by tatthung** [susanBuck/e2-fall20#11]
Hi Guys, @susanBuck,

Since I am using a PC, "sudo" is not working for me, so I tried editing my Hosts file using "Elevante" but it showed error by saying:

```
'elevante' is not recognized as an internal or external command,
operable program or batch file.
```

Any idea how can this be fixed?  If this step is not fixed, i cannot see anything on https://e2p1.loc/

**Comment by tatthung** [comment]
Ops, i think i found out what is the error. It should be Elevate, not "Elevante" (written on notes). All good now.

**Comment by susanBuck** [comment]
So sorry for that typo! Just corrected it.
