### ISSUE TITLE
Issue when running migrations after setting up production database

### ISSUE THREAD

**Issue by pranjal-joshi97** [susanBuck/e2-fall20#111]
Hello! 
I've set up the database for my p3 but when I run migrations, I get the following: 
![image](https://user-images.githubusercontent.com/42822597/101588727-9696f100-3a19-11eb-825f-20cfb555b716.png)
Link to my p3 repository just in case (everything is up to date): https://github.com/pranjal-joshi97/e2/tree/master/p3 

What can I do to fix this? 

Thanks!

**Comment by susanBuck** [comment]
Hi @pranjal-joshi97 -

Can you run `composer install --no-dev` on production within your `p3` directory?

Ref: https://hesweb.dev/e2/notes/php/frameworks/deploy#vendor

I suspect that's the problem as the error is making reference to a Composer file. If that doesn't fix it, let me know.

**Comment by pranjal-joshi97** [comment]
Yes that worked! I guess I had ran `composer install --no-dev`  in my normal folder and not the ssh root. Thanks so much :)
