### ISSUE TITLE
Minor deployment issue

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#112]
I'm getting this:

![image](https://user-images.githubusercontent.com/53196073/101692289-fef7c980-3a3d-11eb-8a26-35462aff2dce.png)

If 

> apt install composer

 does the same thing how do I **--no-dev**?

:-)

**Comment by susanBuck** [comment]
FYI I moved this question over to our course Issues forum (https://github.com/susanBuck/e2-fall20/issues).

That's where you should post any questions. 

(The only time it'd make sense to post in the [e2 framework issues forum](https://github.com/susanBuck/e2/issues) is if you detected some bug in the e2 framework that you wanted to report.)

**Comment by CrimsonSIS** [comment]
Ah! Wasn't clear on the fpp. Anyway, you were right. I'd initialized everything for the ZipFoods project in another droplet.

Got it working. Check it out: http://e2p3.crimsonsis.me

Still wrestling with the TicTacToe project but the above covers requirements for p3.

Really appreciate your help!

:-)

**Comment by susanBuck** [comment]
Glad it's working now. : )
