### ISSUE TITLE
main or master?

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#115]
I posted 
https://github.com/CrimsonSIS/e2/tree/main/p3

Your exemplar in Canvas is
https://github.com/susanBuck/e2/tree/master/p3

I forget the difference between main and master. Can I make my main master? Futzing with it but your insight might be quicker.

**Comment by CrimsonSIS** [comment]
Aha!

https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/#:~:text=GitHub%20repositories%20are%20where%20users,of%20a%20source%20code%20repository.&text=1%2C%202020%2C%20any%20new%20repositories,master%2C%22%20the%20company%20said.

> Starting next month, all new source code repositories created on GitHub will be named "main" instead of "master" as part of the company's effort to remove unnecessary references to slavery and replace them with more inclusive terms.

**Comment by susanBuck** [comment]
Ah yes, that change came about earlier in the semester.

I have so many notes/screenshots to update now 🤦‍♀️ (it's a good change, though, so worth the effort : )
