### ISSUE TITLE
no display on production server

### ISSUE THREAD

**Issue by scoutperry** [susanBuck/e2-fall20#117]
This might be that thing where is takes some time to 'click' but I went through the notes for setting up the production server including the troubleshooting section, I wasn't able to get the production server to display

Virtual host;

    <VirtualHost *:80>
        ServerName e2p3.scoutperry.me
        DocumentRoot "/var/www/html/e2/p3"
        <Directory "/var/www/html/e2/p3">
            AllowOverride All
            Options -Indexes
            Require all granted
        </Directory>
    </VirtualHost>

Cache;

    drwxr-xr-x  2 www-data root  4096 Dec 10 16:19 cache/

Vendor;

    drwxr-xr-x 14 root     root  4096 Dec 10 20:51 vendor/

.env;

    APP_NAME='p3'
    APP_URL='http://e2p3.scoutperry.me'

    DB_NAME='myapp'
    DB_USERNAME='root'
    DB_PASSWORD=''

Thanks,
Scout

**Comment by susanBuck** [comment]
Hi @scoutperry - Can you confirm you restarted Apache after editing your Virtual Hosts file?

```
service apache2 restart
```

If it's still not working after doing that, run `apachectl -S` which will report back on any potential errors in your VirtualHosts config ([ref](https://hesweb.dev/e2/notes/production-server/production-domains#troubleshooting))

**Comment by susanBuck** [comment]
Oh, also, the _DocumentRoot_ and _Directory path_ should point to `/var/www/html/e2/p3/public` instead of just `/var/www/html/e2/p3` ([ref](https://hesweb.dev/e2/notes/php/frameworks/deploy#virtualhosts))

E.g.:

```
<VirtualHost *:80>
    ServerName e2p3.scoutperry.me
    DocumentRoot "/var/www/html/e2/p3/public"
    <Directory "/var/www/html/e2/p3/public">
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>
```

**Comment by scoutperry** [comment]
Ok, switching to public (was i supposed to do that for the other projects? oops) and another apache restart seems to have done it! ***Thank you!!***

**Comment by susanBuck** [comment]
Only on projects that use the e2framework, so not p1 or p2.  But yes for p3 and zipfoods example.

(It's a common practice for frameworks to point to a public/ directory.)
