### ISSUE TITLE
Trouble with seeding a random number for three columns.

### ISSUE THREAD

**Issue by britney-sandau** [susanBuck/e2-fall20#118]
Hi,

I am finishing up my "paper, scissors, rock" game and was trying to figure out a way to seed my data to show who won. I have a column in my database for "player wins", "pc wins", and a "tie". I was using the rand(0, 1) to make sure I could seed data. Now I want to make it where only a "1" shows up in a column, while the other two have "0's", for when I call the seed function from command line. 

I am thinking the only way to do this is to add my code logic to the seed function, but I was checking to see if there was a better way. I was also thinking of extending my class for my seed function to include "class AppCommand extends AppController" to see if that might be a way to grab the code logic from my AppController. 

I should note my code works if I am playing the game. It will enter the data into my database correctly, just not when I want to seed fake games. Thank you for any feedback you can provide.

![image](https://user-images.githubusercontent.com/57762932/101951962-e4505c80-3bc5-11eb-9767-7cf248df25f6.png)

**Comment by britney-sandau** [comment]
I was able to get the correct results when I seed my data by adding my code logic within the seed function. I am thankful it works! :) I am not sure if this will be acceptable. If not please let me know. I will close out this comment in a day.

**Comment by susanBuck** [comment]
Glad you found a workable solution. :) 

Just as food for thought, here's an example of how to continually pick three random values from the options of 1, 0, 0 (without having to pull in game logic):

```php
$outcomes = [1, 0, 0];
        
for ($i = 0; $i < 10; $i++) {
    // Randomize our possible outcomes for each iteration
    shuffle($outcomes);

    $round = [
        'win' => $outcomes[0],
        'pcWin' => $outcomes[1],
        'tie' => $outcomes[2],
    ];

    dump($round);
}
```

On a somewhat related note: I think the three fields of `win`, `pcWin`, and `tie` could really be simplified down to one field, `outcome` where it stores a value of either `pc`, `player`, or `tie`.

Not suggesting you have to refactor your project to do this, I just wanted to throw it out there as we think about code design. : )

**Comment by britney-sandau** [comment]
Thank you so much! This helps out a lot!
