### ISSUE TITLE
Can't install new e2framework project

### ISSUE THREAD

**Issue by emmyzon** [susanBuck/e2-fall20#119]
When running the composer create-project command I'm getting the following error: 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - susanbuck/e2core[0.1.0, ..., 0.1.9] require dflydev/dot-access-data ^2.0 -> satisfiable by dflydev/dot-access-data[v2.0.0].
    - dflydev/dot-access-data v2.0.0 requires php ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires susanbuck/e2core ^0.1.0 -> satisfiable by susanbuck/e2core[0.1.0, ..., 0.1.9].

I also noticed that my zipfoods practice project is no longer running on my local server. Any suggestions?

**Comment by emmyzon** [comment]
nevermind - think I figured it out!

**Comment by susanBuck** [comment]
@emmyzon - Glad you got it sorted out. :)
