### ISSUE TITLE
Unable to link https://e2p2.loc to the correct index.php file

### ISSUE THREAD

**Issue by tatthung** [susanBuck/e2-fall20#12]
Dear @susanBuck,

I was wondering if this only happening on a non-Macintosh system. I was setting up the e2p1.loc localhost link and instructed the Virtual host (in the below) to show the index.php file contained in: 

> **xampp > htdocs > e2 > p1 > index.php**

Here is how i instructed the Virtual host, and restarted XAMPP:

```
<VirtualHost *:80>
        ServerName e2p1.loc
        DocumentRoot c:\xampp\htdocs\e2\p1
        <Directory c:\xampp\htdocs\e2\p1>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
        </Directory>
</VirtualHost>
```

However, when I use the https://e2p1.loc URL,  it directed me to another index.php file:

> **xampp > htdocs > index.php**

Something is odd; on the XAMPP control panel, if i clicked on the Admin button (highlighted in red), then system will direct me to the right index.php

![image](https://user-images.githubusercontent.com/10286253/93013210-e0b63500-f5d8-11ea-9b6c-563c0ad1556e.png)

Do you know what is the issue? Thank you!

**Comment by susanBuck** [comment]
Hi @tatthung -

Try accessing it via `http` instead of `https`..... 

**http://e2p1.loc**

Getting `https` (secure http) to work would require additional steps which we haven't covered. Later in the semester, I'll share information on setting up https on production.

**Comment by tatthung** [comment]
Thanks @susanBuck, you are awesome! My issue has been solved!
