### ISSUE TITLE
Notes for offline reading

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e2-fall20#120]
@susanBuck 

Hi Susan,

Will you be able to provide notes files to us incase we loose access the the Canvas?

Thank you

**Comment by susanBuck** [comment]
Hi @maqboolk -

Revisit the [Week 14](https://hesweb.dev/e2/week/14) Part 1 Video - I speak to the course archive I'll be providing students.

**Comment by maqboolk** [comment]
Thank you.
