### ISSUE TITLE
Which DigitalOcean option to choose?

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#14]
Looks a little different from the video. Should I pick **Ubuntu server** or **PHP (LAMP) app**?

![image](https://user-images.githubusercontent.com/53196073/93252567-ab8a1e00-f763-11ea-8d07-c5932074a989.png)

**Comment by susanBuck** [comment]
Hi @CrimsonSIS -

In the video I followed this link from the notes to get to the correct LAMP setup:

![image](https://user-images.githubusercontent.com/237711/93256216-03775380-f769-11ea-8c66-f4899a7cf5ff.png)

Give that a shot and you should see the correct setup, which is LAMP on Ubuntu 20.04.

**Comment by CrimsonSIS** [comment]
K.

I signed up for the **Student Developer** option in GitHub and it threw me onto that other screen. 

The GitHub option won't be approved until October 24th! 

After going through all that and confirming my email, I went back in following the link in the notes (which takes one to the screen you depicted), and it stated I had a $100 credit(!).

Such a deal...

![image](https://user-images.githubusercontent.com/53196073/93329566-614c7f80-f7eb-11ea-91d2-2410feec6ce4.png)

**Comment by susanBuck** [comment]
Ah, I wasn't aware DO was now giving away credits on sign up. Nice!

Here's info I found on it from their [pricing FAQ](https://www.digitalocean.com/pricing/):

![image](https://user-images.githubusercontent.com/237711/93355031-a1235f00-f80b-11ea-9fda-8199bb1a6922.png)

So the good news is you automatically get $100 in credits; the bad news is it expires after 60 days, so it'll only carry you through the first 2 months of the semester. On the plus side, though, the Github Student Dev pack should come through by then! :-)

**Comment by tatthung** [comment]
I was thinking of what to do after the 2 months $100 credit too, thank you for suggestion!
