### ISSUE TITLE
Accessing http://practice.loc on port 8888?

### ISSUE THREAD

**Issue by alysonann** [susanBuck/e2-fall20#16]
I haven't made it through all the material yet, so apologies if this is covered later, but I need to use port 8888 for my local host, and [http://practice.loc](http://practice.loc) wasn't working. With the help of [this site](https://www.taniarascia.com/setting-up-virtual-hosts/) I figured out I could get [http://practice.loc](http://practice.loc) to work by using [http://practice.loc:8888/](http://practice.loc:8888/). I had changed the first line of the VirtualHost block as follows:
```html
<VirtualHost *:8888>
    ServerName practice.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/practice
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/practice>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>
```
Am I missing something in editing the port? Is [http://practice.loc:8888/](http://practice.loc:8888/) acceptable, or should I go a bit farther to try and make [http://practice.loc](http://practice.loc) work? I'm not sure why port 80 doesn't work for me (last week I couldn't figure out what is using it), but I'd rather not mess with it if I don't have to. Thanks!

**Comment by susanBuck** [comment]
Using port 8888 is fine. 

I specify in the notes that the VirtualHost should be edited if you're using a different port, however, I should elaborate on this to specify you would then have to access the domain via `http://practice.loc:8888`, just as you would access `http://localhost:8888`. Updating the notes now to include this. Thanks for drawing my attention to it @alysonann!
