### ISSUE TITLE
Week 2 - Sep 10 Video Part 6: Production domain video not working

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#17]
![image](https://user-images.githubusercontent.com/53196073/93355046-a7194000-f80b-11ea-9ff0-02fae0100d52.png)

![image](https://user-images.githubusercontent.com/53196073/93355622-450d0a80-f80c-11ea-8b5d-242840483233.png)

**Comment by susanBuck** [comment]
Checking on this now - will report back shortly.

**Comment by susanBuck** [comment]
Try refreshing the page. I had to do a re-upload of that video because of an audio sync problem. The updated link should point to <https://www.youtube.com/embed/jyjF4V6tQm8?rel=0&showinfo=0> (from your screenshot it looks like it's still pointing to the old video).

**Comment by deleonl4** [comment]
I just checked it on different browsers including my phone and it works. Maybe trying a different browser?

**Comment by CrimsonSIS** [comment]
It **is** working in Connecticut from the **Notes** page.

Thanks for the quick response...

:-)
