### ISSUE TITLE
Domain cost: $10 per year not month...

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#18]
No biggie but roughly 3 minutes in...

**Comment by susanBuck** [comment]
Thanks for pointing this out. : )

For context: @CrimsonSIS is referring to the [Week 2, Part 6](https://www.youtube.com/embed/jyjF4V6tQm8?rel=0&showinfo=0) video on production domains in which I misspoke and said that domains cost on average $10 per month. I should have said "per year".
