### ISSUE TITLE
Redirect from existing account question...

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#19]
I registered **crimsonsis.com** at _WebHostingBuzz_ (WHB) last year and parked it.

The only way I can redirect it to my _DigitalOcean_ directory is as follows:

![image](https://user-images.githubusercontent.com/53196073/93376266-56afdb80-f827-11ea-8c6d-66491c591579.png)

WHB's default name server points to it and it is transferring to the correct IP address.

![image](https://user-images.githubusercontent.com/53196073/93376722-038a5880-f828-11ea-8ed8-feb70be68b82.png)

The **index.php** file is not rendering. I'll rewatch the video but any ideas to clue me in?

It does render if I type the IP address in manually.

Enjoying the course!

:-)

**Comment by CrimsonSIS** [comment]
Ah! If I leave the **s** off **https** in the address it resolves.

**Comment by susanBuck** [comment]
Good detective work! : ) Setting up a domain to work with HTTPS takes some extra configuration steps which we'll cover later in the semester.
