### ISSUE TITLE
Git on Mac - invalid active developer path

### ISSUE THREAD

**Issue by deleonl4** [susanBuck/e2-fall20#20]
Hi everyone,

I'm having the issue below when typing git on Command Line. Any suggestions?
I tracked the path and there is only 1 document called "whatis" within "CommandLineTools"

<img width="605" alt="Screen Shot 2020-09-16 at 8 38 53 PM" src="https://user-images.githubusercontent.com/47702390/93406161-02275300-f85d-11ea-9c2f-466e8eae0e46.png">

Ran
xcode-select --install and received this:
<img width="963" alt="Screen Shot 2020-09-16 at 8 45 33 PM" src="https://user-images.githubusercontent.com/47702390/93406438-a90bef00-f85d-11ea-92d9-3b1bbc2faa60.png">

When trying: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
I was prompted with a password, same happened when I tried downloading it with several downloads but it won't let me type anything in.

<img width="581" alt="Screen Shot 2020-09-16 at 8 53 44 PM" src="https://user-images.githubusercontent.com/47702390/93406863-c1303e00-f85e-11ea-934c-9c1a8953299e.png">

**Comment by mborjon** [comment]
Hello, do you have Xcode downloaded? I had to download it.  You can download it from the Mac App Store on your computer.  Be patient, Apple launched a bunch of OS's today so the servers seem a bit slow for downloads/updates.

**Comment by deleonl4** [comment]
Thank you @mborjon! I was having issues downloading it because of space needed and looked into some forums that had the same issue but I guess it just needed time because it finally worked this morning!

**Comment by susanBuck** [comment]
We're debugging this issue on thread #23 so I'm going to close this thread to avoid confusion.
