### ISSUE TITLE
Restarted server but still getting Access forbidden on http://e2p1.loc/

### ISSUE THREAD

**Issue by walshkelsey** [susanBuck/e2-fall20#21]
I have gone over this multiple times and cannot for the life of me figure out what I'm doing wrong. Working out of Terminal. 

Here is my VirtualHost Block:

```
<VirtualHost *:80>
    ServerName e2p1.locc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/p1
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/p1>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>
```

And my host, edited with sudo nano

```
127.0.0.1 e2p1.loc
```

All files are in the correct folder and I have restarted my server multiple times and cannot for the life of me figure out what I'm doing wrong as the practic.loc exercise worked perfectly for me.

**Comment by susanBuck** [comment]
In your VirtualHost block you've got two c's in the ServerName: `e2p1.locc` should be `e2p1.loc` : )

**Comment by walshkelsey** [comment]
Welp. Apparently I need more coffee before server set up 🤦  Thanks for the quick help!

**Comment by susanBuck** [comment]
np - we've all been there! : )
