### ISSUE TITLE
Issue with XAMPP index file?

### ISSUE THREAD

**Issue by mborjon** [susanBuck/e2-fall20#25]
Hello, 

From the browser, my local domains, practice.loc and new e2p1.loc, both result in _Hello from my XAMPP-powered server!_ page from last week's class.  This is what is in the index.php file (/Applications/XAMPP/xamppfiles/htdocs), which is up 2 levels from where the index.php files reside for p1 (/Applications/XAMPP/xamppfiles/htdocs/e2/p1) and practice (/Applications/XAMPP/xamppfiles/htdocs/e2/practice). Please advise how I get the domains to direct to the correct index.php file.

Thanks,
-Melinda 
<img width="987" alt="Screen Shot 2020-09-17 at 5 26 51 PM" src="https://user-images.githubusercontent.com/38201146/93541953-ab795200-f90c-11ea-8495-d88ef97a6b0f.png">
<img width="1501" alt="Screen Shot 2020-09-17 at 5 28 45 PM" src="https://user-images.githubusercontent.com/38201146/93541981-bf24b880-f90c-11ea-8ba8-652b089e61c7.png">
<img width="1569" alt="Screen Shot 2020-09-17 at 5 29 39 PM" src="https://user-images.githubusercontent.com/38201146/93541987-c4820300-f90c-11ea-90ee-de549bb5b57e.png">
<img width="1649" alt="Screen Shot 2020-09-17 at 5 40 46 PM" src="https://user-images.githubusercontent.com/38201146/93542061-f09d8400-f90c-11ea-988b-b53175830c55.png">

**Comment by tatthung** [comment]
Hi @mborjon,

I had the same issue last week, both https://practice.loc and https://e2p1.loc link you to the same index.php (they should link to different index.php), and what i did was 
1. follow steps from https://hesweb.dev/e2/notes/local-server/local-domains to set up localhost for both practice.loc and e2p1.loc, 
2. start XAMPP, and
3. http://e2p1.loc (remove the '**s**' from the URL, just use http://).

**Comment by susanBuck** [comment]
Hi @mborjon - 

When we try to access a domain (or sub-domain) set up via a VirtualHost but it just points to the server's main document root instead of the intended application's document root it means the following two things:

1. The configuration routing the domain to a given IP address is correctly set up (as evidence of the fact that we're at least seeing the main document root).
2. The VirtualHost that should be filtering traffic to that domain to a specific document root is **not** correctly set up (because we're seeing the main document root instead of the app-specific document root).

To help you debug this can you share the full contents of your local VirtualHost config file (`/Applications/XAMPP/etc/extra/httpd-vhosts.conf`)?

Also, just to double check, confirm you've restarted Apache after making any VirtualHost changes.

**Comment by mborjon** [comment]
Hello @susanBuck, 

Below is the contents of /Applications/XAMPP/etc/extra/httpd-vhosts.conf.  

Thank you,
Melinda

```
<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot "/Applications/XAMPP/xamppfiles/docs/dummy-host.example.com"
    ServerName dummy-host.example.com
    ServerAlias www.dummy-host.example.com
    ErrorLog "logs/dummy-host.example.com-error_log"
    CustomLog "logs/dummy-host.example.com-access_log" common
</VirtualHost>

<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host2.example.com
    DocumentRoot "/Applications/XAMPP/xamppfiles/docs/dummy-host2.example.com"
    ServerName dummy-host2.example.com
    ErrorLog "logs/dummy-host2.example.com-error_log"
    CustomLog "logs/dummy-host2.example.com-access_log" common
</VirtualHost>

<VirtualHost *:80>
    ServerName practice.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/practice
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/practice>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName e2p1.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/p1
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/p1
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>
```

**Comment by mborjon** [comment]
> Hi @mborjon,
> 
> I had the same issue last week, both https://practice.loc and https://e2p1.loc link you to the same index.php (they should link to different index.php), and what i did was
> 
> 1. follow steps from https://hesweb.dev/e2/notes/local-server/local-domains to set up localhost for both practice.loc and e2p1.loc,
> 2. start XAMPP, and
> 3. http://e2p1.loc (remove the '**s**' from the URL, just use http://).

Thanks. I already followed the directions in the notes.  And, sorry the "s" was a typo.  It should be http://practice.loc and http://e2p1.loc.

**Comment by susanBuck** [comment]
Hi @mborjon - 

I replaced the contents of my VirtualHosts config file with the contents you shared, and it worked fine - this eliminates (or at least greatly reduces) the possibility that there is some error within that file.

My next thought is maybe that file is not being read.

To check this - can you open your Apache config file at `/Applications/XAMPP/xamppfiles/etc/httpd.conf` and confirm the line including the VirtualHost config file is *not* commented-out.

I.e. instead of this:

```
# Virtual hosts
#Include etc/extra/httpd-vhosts.conf
```

It must look like this:
```
# Virtual hosts
Include etc/extra/httpd-vhosts.conf
```

Once you confirm that, save changes to that file, restart Apache from the XAMPP control panel window, and try again.

If that does not do the trick, would you like to set up a time to do a Zoom screenshare on Monday to debug in real-time? If so, drop me an email (susanbuck@fas.harvard.edu) and we can schedule something.

**Comment by susanBuck** [comment]
I thought of something else to try... Run the following command:

```
/Applications/XAMPP/bin/httpd -S
```

This will give us some debugging info about how Apache is configured. Specifically, we want to confirm it is reading from your `httpd-vhosts.conf` config file.

For reference/comparison, here's what the output looks like on my machine:

```
/Applications/XAMPP/xamppfiles/htdocs   $ /Applications/XAMPP/bin/httpd -S
AH00112: Warning: DocumentRoot [/Applications/XAMPP/xamppfiles/docs/dummy-host.example.com] does not exist
AH00112: Warning: DocumentRoot [/Applications/XAMPP/xamppfiles/docs/dummy-host2.example.com] does not exist
AH00112: Warning: DocumentRoot [/Users/Susan/Sites/hes/dwa-bash/students/anna/e15/p3/public] does not exist
VirtualHost configuration:
*:443                  is a NameVirtualHost
         default server hesweb.loc (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:155)
         port 443 namevhost hesweb.loc (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:155)
         port 443 namevhost courseintros.loc (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:170)
*:80                   is a NameVirtualHost
         default server dummy-host.example.com (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:23)
         port 80 namevhost dummy-host.example.com (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:23)
                 alias www.dummy-host.example.com
         port 80 namevhost dummy-host2.example.com (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:32)
         port 80 namevhost practice.loc (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:40)
         port 80 namevhost e2p1.locc (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:50)
         port 80 namevhost susanbuck.loc (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:198)
         port 80 namevhost localhost (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:227)
ServerRoot: "/Applications/XAMPP/xamppfiles"
Main DocumentRoot: "/Applications/XAMPP/xamppfiles/htdocs"
Main ErrorLog: "/Applications/XAMPP/xamppfiles/logs/error_log"
Mutex default: dir="/Applications/XAMPP/xamppfiles/logs/" mechanism=default 
Mutex mpm-accept: using_defaults
Mutex authdigest-opaque: using_defaults
Mutex proxy-balancer-shm: using_defaults
Mutex ssl-stapling-refresh: using_defaults
Mutex rewrite-map: using_defaults
Mutex authdigest-client: using_defaults
Mutex ssl-stapling: using_defaults
Mutex ldap-cache: using_defaults
Mutex proxy: using_defaults
Mutex ssl-cache: using_defaults
Mutex authn-socache: using_defaults
PidFile: "/Applications/XAMPP/xamppfiles/logs/httpd.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
Define: MODPERL2
User: name="Susan" id=502 not_used
Group: name="daemon" id=1 not_used
```

**Comment by mborjon** [comment]
@susanBuck  

I re-verified that the line including the VirtualHost config file is *not* commented-out and restarted Apache again.  It did not fix the issue.  

I ran /Applications/XAMPP/bin/httpd -S and below is what I got:

Melindas-MBP:~ melindaheinlein$ /Applications/XAMPP/bin/httpd -S
AH00112: Warning: DocumentRoot [/Applications/XAMPP/xamppfiles/docs/dummy-host.example.com] does not exist
AH00112: Warning: DocumentRoot [/Applications/XAMPP/xamppfiles/docs/dummy-host2.example.com] does not exist
AH00526: Syntax error on line 53 of /Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:
<Directory> directive missing closing '>'
Melindas-MBP:~ melindaheinlein$

**Comment by susanBuck** [comment]
The output you shared indicates there's a syntax error in your file VirtualHosts config file:

```
AH00526: Syntax error on line 53 of /Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:
directive missing closing '>'
```

Try fixing that and restarting Apache again. Also, run `/Applications/XAMPP/bin/httpd -S` again to confirm the error is gone.

**Comment by mborjon** [comment]
@susanBuck That worked. Thank you!
