### ISSUE TITLE
localhost/e2/practice not opening on web browser 

### ISSUE THREAD

**Issue by pranjal-joshi97** [susanBuck/e2-fall20#27]
Hello, 
I'm getting the following error when opening up localhost/e2/practice and other localhost links in my web browser. 
![image](https://user-images.githubusercontent.com/42822597/93581634-9adbe100-f9cb-11ea-930f-5be828b153f2.png)

I'm confused because I haven't made changes to my xampp/htdocs folder. Is it do with my internet connection or a fault somewhere in my xampp/htdocs folder? 

Would appreciate any input on this :) 
Thanks!

**Comment by pranjal-joshi97** [comment]
Never mind I figure it out! I forgot to turn on Apache on the XAMPP control panel.

**Comment by susanBuck** [comment]
Glad you got it figured out, @pranjal-joshi97! :-)
