### ISSUE TITLE
Unable to point to /var/www/html/e2/p1

### ISSUE THREAD

**Issue by tatthung** [susanBuck/e2-fall20#28]
Hi @susanBuck and classmates,

My current domain (http://tatthung.me) is showing the default index.php file , the one that comes with DigitalOcean. I have edited the index page and now it is showing a default index page crafted last week.

Today, i edited the 000-default.conf

> $ nano /etc/apache2/sites-enabled/000-default.conf

```
<VirtualHost *:80>
    ServerName e2p1.tatthung.me
    DocumentRoot "/var/www/html/e2/p1"
    <Directory "/var/www/html/e2/p1">
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>
```
I still get the same default index page. Anyone know how can I fix this problem? 

Many thanks,
Tatt

**Comment by susanBuck** [comment]
Hi @tatthung -

I'm going to test your VirtualHost config block on my end to confirm there aren't any errors we're not seeing.

In the meantime, can you confirm you restarted Apache on your production server after adding the VirtualHost?

![image](https://user-images.githubusercontent.com/237711/93618910-ea0f1b00-f9a5-11ea-8437-863d65ac0ae5.png)

**Comment by susanBuck** [comment]
Follow-up:

I copied your VirtualHost block exactly as you wrote it in this post into my settings. I only changed `e2p1.tatthung.me` so it used my domain `e2p1.hesweb.xyz`.

I saved the settings, restarted Apache (`service apache2 restart`) and confirmed the subdomain <http://e2p1.hesweb.xyz> was pointing to the expected location.

Given this, we can assume there are no errors in your VirtualHost block.

If confirming Apache was restarted by restarting it again doesn't do the trick, share the full contents of your server's VirtualHost config file (`/etc/apache2/sites-enabled/000-default.conf`) in this thread - perhaps there's something else in the file that is preventing this from working.

**Comment by tatthung** [comment]
Hi @susanBuck ,

Unfortunately, restarting Apache did not work. Here is a screenshot of my `000-default.conf script`.

![image](https://user-images.githubusercontent.com/10286253/93657772-d4622a00-fa67-11ea-8d51-dd0c551f63bd.png)
![image](https://user-images.githubusercontent.com/10286253/93657827-52becc00-fa68-11ea-97c7-95589122c1c7.png)


I also tried changing * to e2p1 in the Host field, but still no luck.

![image](https://user-images.githubusercontent.com/10286253/93657851-97e2fe00-fa68-11ea-8fb6-9a6e71cb3c0b.png)

**Comment by tatthung** [comment]
@susanBuck , I think you are right, my issue has been fixed automatically after waiting for a day. I guess this is due to server delay! Thank you so much for spending time duplicating the files and debug for me!

**Comment by susanBuck** [comment]
Glad to hear it! : )
