### ISSUE TITLE
New Apache config setting not working.

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e2-fall20#30]
Hi all,
Is new Apache Config setting working for anyone?

```
<VirtualHost *:80>
    ServerName practice.loc
    DocumentRoot /path/to/htdocs/e2/practice
    <Directory /path/to/htdocs/e2/practice>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName e2p1.loc
    DocumentRoot /path/to/htdocs/e2/p1
    <Directory /path/to/htdocs/e2/p1>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>
```

I updated my **httpd-vhosts.conf** file with above setting and its giving me **Access forbidden!** page, and its because of the **Options -Indexes**. 

Is there any other steps I need to follow?

I also confirmed my DocumentRoot and it is pointing to   **"/Applications/XAMPP/xamppfiles/htdocs"**.

Note: I am using XAMPP 7.4.1-1

**Comment by susanBuck** [comment]
@maqboolk -

Make sure you update the paths to match your system - `/path/to/htdocs/e2/p1` is just an example.

If you're using a Mac, it would be something like:

```
/Applications/XAMPP/xamppfiles/htdocs/e2/p1
```

If you're using Windows, it would be something like:

```
c:\xampp\htdocs\e2\p1
```

These paths are reflected in the notes here: 
https://hesweb.dev/e2/notes/local-server/local-domains#step-2-virtualhost-entry

**Comment by maqboolk** [comment]
@susanBuck Thank you!
