### ISSUE TITLE
Getting a PHP CS Fixer general error whenever I try to save my vscode file

### ISSUE THREAD

**Issue by pranjal-joshi97** [susanBuck/e2-fall20#35]
Hello, 
This is related to the php extension we installed for the week 4 lecture. After installing the extension I'm getting the following error message whenever I save the file: 
![image](https://user-images.githubusercontent.com/42822597/94242159-d16fa980-ff3f-11ea-95b2-57e97335d6eb.png)
Did I make a mistake in installing it? 

Appreciate the help!

Pranjal

**Comment by tatthung** [comment]
Hi @pranjal-joshi97,

This is the extension I have installed:
![image](https://user-images.githubusercontent.com/10286253/94244951-2d402f80-ff4c-11ea-9587-445a381193c8.png)

I don't get the your error message, but I have included these additional lines in the `settings.json` file and saved it (I have included this path as a Windows user: c:\Users\YourUsername\.vscode\extensions\junstyle.php-cs-fixer-0.1.156\php-cs-fixer.phar).

![image](https://user-images.githubusercontent.com/10286253/94244384-6330e400-ff4b-11ea-9064-1fbcb52ff137.png)

**Comment by pranjal-joshi97** [comment]
@tatthung Hey thanks for your reply! I think the code provided in the PHP and VSCode notes has back slashes for Windows and that's what was giving me the error. I changed them to forward slashes and it worked out! 
I've emailed Professor Buck about it :)

**Comment by susanBuck** [comment]
Thanks for drawing my attention to this, @pranjal-joshi97! I checked my Windows VSCode install and I was using forward slashes there, so not sure why/how I wrote it in the notes with back slashes. 🤦‍♀️

Just corrected. : )
