### ISSUE TITLE
Interesting read: The Era of Visual Studio Code

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall20#36]
Hi everyone,

I came across an interesting post this morning: [The Era of Visual Studio Code](https://blog.robenkleene.com/2020/09/21/the-era-of-visual-studio-code/)

In the post, the author discusses the evolution of code editors, and makes the case that VSCode might be taking root as a code editor with some longevity. Beyond that, it offers an interesting history of code editors, and also the shift to web based editors.

I agree with many of the points it makes, and wouldn't be sad if I didn't have to learn a new interface every few years. : ) That being said, one thing I will say I dislike about extension-heavy editors, is while they provide a lot of flexibility, it can be a hassle getting things configured how you want - as evidence by some recent posts we've had about plugins/configurations (I also speak to this in this week's videos). 

A few years ago, in any PHP course I was teaching we used an IDE (Integrated Development Environment) by JetBrains called PhpStorm - and as you would expect by the name - it was configured "out of the box" to work very well with PHP. You didn't have to try out/narrow down the best plugins, worry about configuring them, etc.

Anyway, just some misc. food for thought for your Friday afternoon. 

Hope everyone has a nice weekend!

Susan

**Comment by CrimsonSIS** [comment]
Interesting. Giving it a shake. Have been using Sublime. :-)

**Comment by susanBuck** [comment]
@CrimsonSIS - I used Sublime for a while, and still occasionally do. I like it as a "secondary" editor when I have several different projects open. 

Curious to hear how you like VSCode after taking it for a spin this semester!
