### ISSUE TITLE
Terminal not picking up "\ " in ~/Library/Application\ Support/Code/User/settings.json

### ISSUE THREAD

**Issue by walshkelsey** [susanBuck/e2-fall20#37]
I had a hard time finding ~/Library/Application\ Support/Code/User/settings.json but finally got to it by calling each directory one by one. 

When I got to Application Support, it was not recognizing the \ in front of the space. The only was I was able to ope it was 
`Kelseys-Air:Library kelseywalsh$ cd "Application Support"`

I can definitely adapt to using the quotes for the directory name, but just curious if anyone else was having this issue or knows how to get Terminal to recognize the space with a \

**Comment by susanBuck** [comment]
@walshkelsey - Good thinking/troubleshooting by navigating one directory at a time when you had problems with the full path. 👍

That backslash is used to escape the space, making it possible to use that path even though it has a space. This is one technique to deal with spaces - another - as you identified - is to surround the path in quotes.

I ran some tests to try and recreate the issue you were having with the path containing the slash. Here were the results:

I am able to change directly into the directory that contains the `settings.json` file with this command:

```
$ cd ~/Library/Application\ Support/Code/User/
```

(Note how the actual file name, `settings.json` is removed if I'm just trying to move into its directory.)

I can open the settings file for editing via nano like this:

```
nano ~/Library/Application\ Support/Code/User/settings.json
```

Or, if I just want to view the contents of that directory I can use the cat command:

```
cat ~/Library/Application\ Support/Code/User/settings.json
```

In all instances, the presence of the back slash works.

If I navigate to `~/Library` (the parent directory of *Application Support*), I can then get into the *Application Support* directory either using the forward slash *or* surrounding it in quotes:

```
~/Library   $ cd Application\ Support
~/Library/Application Support   $ cd ../
~/Library   $ cd "Application Support"
~/Library/Application Support   $ 
```

Can you recreate the issue you were facing where the backslash wasn't working and share the exact output/error message you were getting?

**Comment by deleonl4** [comment]
I had an issue where my permissions were not sufficient to access the file when using `$ ~/Library/Application\ Support/Code/User/settings.json` but `$ cd ~/Library/Application\ Support/Code/User/` and `nano ~/Library/Application\ Support/Code/User/settings.json` worked for me, thank you!

**Comment by walshkelsey** [comment]
Hi all,

I was not able to recreate the issue, which makes me wonder if I initially had an extra space in there or left the file name in by mistake. I'm still getting used to working in command line (as you've seen from my other posts here) so I think I just need to become more fluent. 

Thank you as always for the assistance!

**Comment by susanBuck** [comment]
No problem. Command line is not at all forgiving, so it can take some practice to get comfortable with it. Keep the questions coming as you face them!
