### ISSUE TITLE
Problem with PHP CS Fixer 

### ISSUE THREAD

**Issue by mborjon** [susanBuck/e2-fall20#39]
@susanBuck. I am seeing the red line now per the previous post (thank you), but am getting this error.  I checked the extension settings and clicked settings.json from that page (in VSCode) and there's a red line under php-cs-fixer.executablePath.  Any insight here?

<img width="461" alt="Screen Shot 2020-09-27 at 1 50 13 PM" src="https://user-images.githubusercontent.com/38201146/94375881-91d5c880-00cb-11eb-91a1-2dde3d6da55a.png">
<img width="1081" alt="Screen Shot 2020-09-27 at 2 05 04 PM" src="https://user-images.githubusercontent.com/38201146/94375883-9306f580-00cb-11eb-857c-b2bb03a5cb78.png">
<img width="984" alt="Screen Shot 2020-09-27 at 2 04 42 PM" src="https://user-images.githubusercontent.com/38201146/94375882-926e5f00-00cb-11eb-890b-ae681ddaee61.png">

**Comment by susanBuck** [comment]
@mborjon If you hover over the red line for a second, I think it should show a message saying "**_Expected comma_**"

The reason is because there is no comma at the end of the `}` that comes before. Try adding that comma and see if the red line goes away.

Some background: The settings file is written in JSON (JavaScript Object Notation) which is just a data format/pattern. Using this pattern, each item in the JSON data should be separated by a comma.

**Comment by susanBuck** [comment]
Follow-up to address the popup saying there's no executable path for php-cs-fixer -

Try removing the square brackets from your path.

So this:
```
"php-cs-fixer.executablePath": "[~/.vscode/extensions/junstyle.php-cs-fixer-0.1.156/php-cs-fixer.phar]",
```

Should be this:
```
"php-cs-fixer.executablePath": "~/.vscode/extensions/junstyle.php-cs-fixer-0.1.156/php-cs-fixer.phar",
```

**Comment by maqboolk** [comment]
> @mborjon If you hover over the red line for a second, I think it should show a message saying "**_Expected comma_**"
> 
> The reason is because there is no comma at the end of the `}` that comes before. Try adding that comma and see if the red line goes away.
> 
> Some background: The settings file is written in JSON (JavaScript Object Notation) which is just a data format/pattern. Using this pattern, each item in the JSON data should be separated by a comma.

@susanBuck 
Do we need to add php settings outside main block or within main block in settings file?

**Comment by susanBuck** [comment]
Within the main block. For reference, here's an example of what my settings.json file looks like:

![image](https://user-images.githubusercontent.com/237711/94464333-5818c680-018c-11eb-8a3c-62ef7bcd4c98.png)

**Comment by maqboolk** [comment]
@susanBuck 
Hi Susan, 
My extension seems to be partially working. It does not format "...view.php" file for me. It removes the trailing **?>** in controller file when I try to save but does not do anything for my view file. My html code stays the same and does not format as expected.


Attached is the screenshot of my settings.json file.

![image](https://user-images.githubusercontent.com/3629441/94465775-6a93ff80-018e-11eb-989c-9bb434239cd7.png)

**Comment by mborjon** [comment]
@maqboolk and @susanBuck, in the settings for the extension, it mentions php-cs-fixer without the version number. Do we need the version number?

**Comment by susanBuck** [comment]
You can try it with and without version numbers. 

Without version numbers is more straightforward, of course. The reason I don't suggest that approach is because in past semesters we ran into issues with it not working for some students. Whereas with version numbers (assuming it's set correctly), it consistently worked.

**Comment by mborjon** [comment]
@susanBuck 
<img width="1429" alt="Screen Shot 2020-09-28 at 8 21 06 PM" src="https://user-images.githubusercontent.com/38201146/94509080-52d96d00-01c8-11eb-879d-ac61d3b86be7.png">
I added the comma, but now the error has moved to the comma?  Any thoughts?  It says 'End of File expected' when I roll over it.

Thanks!

**Comment by maqboolk** [comment]
@mborjon 

All settings should be enclosed within **{    }** block/brackets. Your PHP settings that you added are out side of the **{  }** block. 

Steps to fix your settings file.

1. Add a comma at the end of line 8
2. Remove comma, that you added at the end of line 9 after **}**
3. Now, you can either move the **}** after all of your PHP settings OR cut your PHP settings and paste them after line 8 and Save.

Good luck.

**Comment by mborjon** [comment]
@maqboolk Thank you. That worked!

**Comment by susanBuck** [comment]
I just re-wrote the [VSCode and PHP](https://hesweb.dev/e2/notes/misc/vscode-and-php) notes to simplify the entire process and also better explain how the settings should be added. 

Before, I was making too many assumptions pre-existing knowledge of JSON syntax - apologies for that. I've also included a good/simple reference to JSON if it's something you're new to: https://www.elated.com/json-basics/.

@maqboolk - As part of this re-write, I also addressed how to get it to format your `*-view.php` files which are primarily HTML code. In summary, you need to add this additional setting:

```json
// Tell VSCode to format files ending in `-view.php` as HTML files (since they primarily contain HTML)
"files.associations": {
    "*-view.php": "html"
},
```

Thanks everyone for your help as I work out the kinks of this new noteset - appreciate the patience and feedback!

**Comment by maqboolk** [comment]
@susanBuck -  VSCode formats my **-view.php** file as HTML. Thank you

**Comment by susanBuck** [comment]
Thanks for confirming @maqboolk!

**Comment by deleonl4** [comment]
This thread was really helpful. I ran into similar issues not knowing where exactly to add the PHP code. Thank you for clarifying!
