### ISSUE TITLE
Tip: Toggle White Space Characters

### ISSUE THREAD

**Issue by mborjon** [susanBuck/e2-fall20#40]
Hello All,

I figured out how to show whitespace characters in VSCode, like @susanBuck does in her videos. Go to keyboard shortcuts (in settings) and search for Toggle Whitespace.  There you can set a keybinding and once you use it, it will be toggled on.

Hope this helps!

-Melinda

<img width="691" alt="Screen Shot 2020-09-27 at 4 42 42 PM" src="https://user-images.githubusercontent.com/38201146/94379034-92c62480-00e2-11eb-989b-ad691b4c2f33.png">

**Comment by susanBuck** [comment]
Thanks for sharing this tip, @mborjon!

Some find the extra characters showing white space to be distracting - I like it though, as it emphasizes any problems in my indentation, and reveals any inconsistencies between indentations within a file (e.g. tabs vs. spaces).

**Comment by chuckac** [comment]
In the theme of tips and tricks, I learn about Alt+click in VSCode, which was awesome in editing an array.  Hold Alt and click the lines were you intend to type the exact same thing, and you can enter the same information by typing on multiple lines at the same time.

**Comment by susanBuck** [comment]
Closed this thread, but if you encounter any other tips/trick you want to share, don't hesitate to create a new one!
