### ISSUE TITLE
phpCSfixer - where to manually install

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#42]
Noticed that **phpCSFixer** is preinstalled in the latest Macintosh version of VSCode.

See below.

![phpCSFixer](https://user-images.githubusercontent.com/53196073/94578082-4810ed80-0245-11eb-8f31-48dde07ac1ec.png)

I downloaded the ZIP of the installer using the link provided in the notes.

Can probably find a YouTube video on this or poke around in the Applications folder, but is there a place to stick it to do a manual install?

:-)

**Comment by susanBuck** [comment]
@CrimsonSIS -

If it's already installed, no need to mess with the downloaded zip/manual install.  : )

I'm kind of surprised it's preloaded in new VSCode installations. Any chance you had just done an update on VSCode and it pulled in existing extensions?

Just for reference, here are where extensions live:

+ Mac: `~/.vscode/extensions/`
+ Windows: `c:\Users\YourUsername\.vscode\extensions\`

([ref](https://hesweb.dev/e2/notes/misc/vscode#extensions))

**Comment by CrimsonSIS** [comment]
I downloaded the installer and figured I'd watch a **YouTube** on where to put it, since the link in the Notes is to a repository.

Here's the 3+ minute video: https://youtu.be/PmdbndOoKq4 

The video was disappointing at first, because it just showed how to install a package you can search for by name. 

In the last 40 seconds, however, he mentioned phpCSFixer, then showed the funky name for it in the list. When I searched the funky name, it was, indeed, in the list.

When I clicked on the entry, it only gave the Disable and Uninstall options. 

I took that to mean it was already in my instance.

Nu?

**Comment by susanBuck** [comment]
Yup, I agree the "Disable and Uninstall" option indicates it was already installed. I'm just scratching my head on *how* it was already installed since I don't believe it's a default extension. 

Curious if any other students reading this thread encountered the same thing...?

Regardless of how it got installed, I suppose the important thing is that it is installed. : )
