### ISSUE TITLE
Another VSCode optimization: HTML Code formatting in View .php files

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall20#43]
If you've followed my notes on [VSCode and PHP](https://hesweb.dev/e2/notes/misc/vscode-and-php) you should have the following results:

+ Any syntax issues in .php files are indicated by a red squiggly line
+ PHP code in .php files are correctly auto-formatted

One thing still lacking though, is that our .php View files (e.g. `bank-view.php`) are not being correctly auto-formatted. The reason is because this file is dominantly HTML code, but because it has a .php extension, the HTML formatter is not applying.

To address this, we need to tell VSCode to treat files ending in `-view.php` as HTML files. You can do this by adding the following config to your settings.json file:

```
// Tell VSCode to format files ending in `-view.php` as HTML files (since they primarily contain HTML)
"files.associations": {
    "*-view.php": "html"
},
```

I've rewritten the [VSCode and PHP](https://hesweb.dev/e2/notes/misc/vscode-and-php) notes to streamline the entire config process, and also address this missing point.

Let me know if you have any feedback or issues with this!

**Comment by alysonann** [comment]
I'm not sure why, but my view files are still not showing or auto-formatting php correctly. I have updated my settings.json exactly as shown on the [notes](https://hesweb.dev/e2/notes/misc/vscode-and-php), including the most recent update for HTML files. There is no formatting for things like "echo" and "foreach" loops (even when the code seems to be working!).
<img width="400" alt="Screen Shot 2020-09-30 at 11 22 08 AM" src="https://user-images.githubusercontent.com/31620333/94705569-3562eb00-030f-11eb-9796-57d912b045b7.png">

**Comment by susanBuck** [comment]
Hi @alysonann - This happens because we instructed VSCode to treat `*-view.php` files as HTML code, and thus the HTML formatter, not the PHP formatter is being applied.

I would have thought the php-cs-fixer extension would accomplish this given it offered the following option:

```
"php-cs-fixer.formatHtml": true,
```

However, that does not seem to do the trick. 

I did some digging into a solution for this, and found the plugin: *format-html-in-php* by *rifi2k*:

> This extension provides formatting for the HTML code in PHP files. This way this works is this extension runs right before the save action which triggers any other registered PHP formatting extensions so you are free to have one and this will not get in the way or block it.

Once I installed this plugin, I removed this setting:

```
"files.associations": {
        "*-view.php": "html"
},
```

Reason: With the addition of the format-html-in-php plugin, we can get both HTML and PHP formatting in our View .php files, without having to have VSCode treat them as HTML.

This combination actually seems to do the trick...

+ .php files are properly formatted
+ .php files with HTML code are properly formatted
+ .html files are properly formatted

If you've got a minute to give it a shot on your end, let me know how it goes.

**Comment by alysonann** [comment]
Yes, this worked for me! I am also trying a CSS formatter. I picked the first one that came up--CSS Formatter aeschli.vscode-css-formatter--and that seems to work. Thanks!

**Comment by susanBuck** [comment]
Thanks for testing it out @alysonann! I've edited the notes again to add the suggestion of the *format-html-in-php* extension, and remove the *files.associations* setting. I also spoke to this in the videos I posted yesterday (Week 5).

**Comment by CrimsonSIS** [comment]
FYI
![DGMD_2_Configuration](https://user-images.githubusercontent.com/53196073/95358146-b9c8e700-0896-11eb-9f93-029a8d5c450a.png)

**Comment by susanBuck** [comment]
@CrimsonSIS - That back slash is intentional - it's escaping the space in the path.

**Comment by CrimsonSIS** [comment]
Ah! My bad. Will give it a shot. Futzing with editor later...

**Comment by susanBuck** [comment]
@CrimsonSIS - Ok! Let me know if it gives you any problems. : )

**Comment by CrimsonSIS** [comment]
Got it to work! Been a while since I saw an embedded space in a path. As Martha Stewart would say, "you learn something new every day." :-)
