### ISSUE TITLE
Error message when trying to save files after installing php  cs fixer extension

### ISSUE THREAD

**Issue by walshkelsey** [susanBuck/e2-fall20#44]
I was trying to get my files set up for the first step of creating the game, but it will not let me save them. I keep getting the below error message: 

![Screen Shot 2020-09-29 at 8 21 36 PM](https://user-images.githubusercontent.com/69866282/94630121-c8aa0b00-0292-11eb-94ca-e8ac462b3aa3.png)

I thought I had installed the extension successfully, but now I don't know. I uninstalled the extension and then reinstalled it with the configs in the updated notes, but I am still getting that error message. 

Any advice?

**Comment by kristysunnyd** [comment]
Hi! I'm not entirely sure if this is right, but did you install the correct version of PHP CS Fixer? It should be the one by 'junstyle' that's lowercase :) 

<img width="572" alt="Screenshot 2020-09-30 at 9 39 11 AM" src="https://user-images.githubusercontent.com/54469624/94633750-e44bfa80-0300-11eb-9e2c-ad682f2c48e6.png">

**Comment by susanBuck** [comment]
Hi @walshkelsey - can you share the full contents of your VSCode settings.json file so we can double check everything?

**Comment by walshkelsey** [comment]
@susanBuck here it is:

```
{
    "window.zoomLevel": 0,
    "editor.lineHeight": 0,
    "editor.fontSize": 17,
    "editor.formatOnSave": true
}

"php-cs-fixer.executablePath": "~/.vscode/extensions/junstyle.php-cs-fixer-0.1.156/php-cs-fixer.phar",
"php-cs-fixer.onsave": true,
"php-cs-fixer.rules": "@PSR2",
"php-cs-fixer.formatHtml": true,

{
    // The following 5 lines just demonstrate existing settings you may/may not already have in your settings.json file
    "workbench.startupEditor": "newUntitledFile",
    "editor.formatOnSave": true,
    "editor.insertSpaces": true,
    "editor.tabSize": 4,
    "editor.minimap.enabled": false,

    // ** Config 1 **
    // Tell VSCode where to find PHP so it can identify syntax errors in your code
    "php.validate.executablePath": "/Applications/XAMPP/xamppfiles/bin/php",

    // ** Config 2 **
    // Tell the php-cs-fixer extension where it can find the `php-cs-fixer.phar` executable
    // Also, set some other general settings for the php-cs-fixer extension
    "php-cs-fixer.executablePath": "~/.vscode/extensions/junstyle.php-cs-fixer-0.1.156/php-cs-fixer.phar",
    "php-cs-fixer.onsave": true,
    "php-cs-fixer.rules": "@PSR2",
    "php-cs-fixer.formatHtml": true,

    // ** Config 3 **
    // Tell VSCode to format files ending in `-view.php` as HTML files (since they primarily contain HTML)
    "files.associations": {
        "*-view.php": "html"
    },
}
{
    // The following 5 lines just demonstrate existing settings you may/may not already have in your settings.json file
    "workbench.startupEditor": "newUntitledFile",
    "editor.formatOnSave": true,
    "editor.insertSpaces": true,
    "editor.tabSize": 4,
    "editor.minimap.enabled": false,
```

**Comment by susanBuck** [comment]
Hi @walshkelsey - From what you shared, I see a couple issues:

1. Several of the configs are repeated twice
2. The entire settings block should start with a opening curly bracket `{` and end with a closing curly bracket `}`. 

Here's what it should look like on a Mac:
```
{
    // The following 5 lines just demonstrate existing settings you may/may not already have in your settings.json file
    "workbench.startupEditor": "newUntitledFile",
    "editor.formatOnSave": true,
    "editor.insertSpaces": true,
    "editor.tabSize": 4,
    "editor.minimap.enabled": false,
    
    // ** Config 1 ** 
    // Tell VSCode where to find PHP so it can identify syntax errors in your code
    "php.validate.executablePath": "/Applications/XAMPP/xamppfiles/bin/php",
    
    // ** Config 2 **
    // Tell the php-cs-fixer extension where it can find the `php-cs-fixer.phar` executable
    // Also, set some other general settings for the php-cs-fixer extension
    "php-cs-fixer.executablePath": "~/.vscode/extensions/junstyle.php-cs-fixer-0.1.156/php-cs-fixer.phar",
    "php-cs-fixer.onsave": true,
    "php-cs-fixer.rules": "@PSR2",
    "php-cs-fixer.formatHtml": true,

    // ** Config 3 **
    // Tell VSCode to format files ending in `-view.php` as HTML files (since they primarily contain HTML)
    "files.associations": {
        "*-view.php": "html"
    },
}
```

**Comment by walshkelsey** [comment]
Thank you that seems to have solved it. Do you happen to know of a way to select all and delete text in nano files on Terminal? I think that's what got me, I managed to delete a good amount of the text but did not clear everything out. Most of the shortcuts don't seem to work, and when I do the Ctrl+K to cut line by line, it seems to leave some text I am not seeing on my main window.

**Comment by susanBuck** [comment]
Hm, I'm not sure of a way to delete all text at once using Nano.

As an alternative, though, you could delete the file and then re-create it, effectively clearing it:

```
$ rm ~/Library/Application\ Support/Code/User/settings.json
$ nano ~/Library/Application\ Support/Code/User/settings.json
```

Another thing you could do is install VSCode command line tools ([instructions here...](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line))- this would allow you to easily open text files in VSCode directly from command line. For example, once installed, you could run the following command...

```
$ code ~/Library/Application\ Support/Code/User/settings.json
```

...this would open the settings.json file in VSCode, which will provide a much easier editing experience vs. Nano. : )

**Comment by susanBuck** [comment]
Going to close this post since the original issue is solved - but don't hesitate to keep the discussion going or start a new thread if you have additional questions about working with settings.json!
