### ISSUE TITLE
error: Pulling is not possible because you have unmerged files

### ISSUE THREAD

**Issue by walshkelsey** [susanBuck/e2-fall20#46]
After testing on my local server, I wanted to deploy to my production server for testing. 

I was able to successfully commit my files to my GitHub repository: https://github.com/walshkelsey/e2/tree/master/p1 

However when trying to pull this to my production server I got the following error message: 

```
root@walshe2:/var/www/html/e2# git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```

The files should be appearing on http://p1.kwalsh12.me/. I have restarted my Apache server as well to see if that would do the trick but no such luck. 

Any hints as to what step I'm missing? I've been reviewing the notes on both GitHub and DigitalOcean but can't seem to figure out where I'm going wrong to get this error message.

**Comment by susanBuck** [comment]
Hi @walshkelsey -

Can you run `git status` on production (in your e2) repository and share the output?

It will tell you what files might have changed that are preventing the pull.

**Comment by walshkelsey** [comment]
Here is the output: 
```
root@walshe2:/var/www/html/e2# git status
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:
	modified:   p1/README.md
	new file:   p1/index-view.php
	new file:   practice/bank-view.php
	new file:   practice/bank.php

Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both modified:   p1/index.php
```

**Comment by susanBuck** [comment]
Based on that output, it appears there were some file changes on production.

If you run `git diff filename` (e.g. `git diff p1/index.php`) you can see what the actual changes were.

If the changes are insignificant/you're okay with disregarding them, you can run the following commands to force your production repository to exactly match what is in Github:

```
git fetch --all; git reset --hard origin/master
```

This would resolve the issue with `git pull` not working, as everything would be in sync again.

**Important note about these commands**: They will remove any changes you have to your files on production, so only run them if you're sure you wish to abandon those changes.

If there are changes on production you don't wish to disregard, let me know and we can discuss an alternative set of steps to resolve the conflicts.

**Comment by walshkelsey** [comment]
This resolved the issue. It was just a line of code place on a different line in each file so it was super easy to fix. Thank you!
