### ISSUE TITLE
Quiz 3 Overwrite

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#48]
Hi:

I'm doing Quiz 4 but I think I clicked on Quiz 3 accidentally and overwrote it. 

Was it graded yet?

Oye.

:-|

**Comment by susanBuck** [comment]
Not a problem - I'm grading it tomorrow and will make a note to disregard the inadvertent attempt. 👍

**Comment by CrimsonSIS** [comment]
Phew! :-)
