### ISSUE TITLE
Can't find the code for forms-misc on github

### ISSUE THREAD

**Issue by pranjal-joshi97** [susanBuck/e2-fall20#49]
Hello, 
I can't find the source code for the forms-misc activity from the lecture on GitHub e2/practice repository. 
(I may have missed it too!)

**Comment by susanBuck** [comment]
Hi @pranjal-joshi97 - Apologies for that, forgot to commit it! : )

It's there now: https://github.com/susanBuck/e2/tree/master/practice/form-misc

**Comment by pranjal-joshi97** [comment]
Thanks so much!
