### ISSUE TITLE
Permission Denied Apache Error Log

### ISSUE THREAD

**Issue by pllealfunes** [susanBuck/e2-fall20#5]
Hi guys,

I'm trying to get to Apache's Error Log through the terminal, but I keep getting the message below. The same happens when I try to get to Apache's Configuration file. Any ideas why this could be happening? Thanks.

`-bash: /Applications/XAMPP/xamppfiles/logs/error_log: Permission denied`

**Comment by tatthung** [comment]
Hi, have you tried checking the logs folder permission? Right click the folder, under properties, there is a change permission.

**Comment by pllealfunes** [comment]
Thanks for the suggestion. I changed permissions to `Read and Write` and I still get `permission denied` on my terminal.

**Comment by pllealfunes** [comment]
I think I was able to solve my problem. I used the command `less /Applications/XAMPP/xamppfiles/logs/error_log` and I was able to see the contents of my error log.

**Comment by susanBuck** [comment]
Glad you got it sorted out, @pllealfunes.

It is odd that the `cat` command gave a permissions error while `less` did not. (I'm assuming you were previously using `cat` as that's what is suggested in the question prompt in the assignment. : )

If it happens again, let us know and we can dig deeper into the permissions.
