### ISSUE TITLE
$_SESSION with multiple different keys

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e2-fall20#52]
@susanBuck 

Hi Susan, 

can we use session multiple times
```PHP
$_SESSION['firstName'] = $_GET['firstName'];
$_SESSION['lastName'] = $_GET['lastName'];
$_SESSION['winner'] = $_GET['winner'];
```

instead of an Array?
```PHP
$_SESSION['result'] = [
'firstname' => 'firstname',
'lastName' => 'lastName',
'winner' => 'winner'
]; 
```

**Comment by susanBuck** [comment]
Hi @maqboolk - Absolutely!

**Comment by maqboolk** [comment]
@susanBuck 

Follow up question. Will it create multiple files to store each data?

**Comment by susanBuck** [comment]
Good question -

No, it will not create multiple files. There's one session file per visitor, in which multiple values may be encoded.
 
FYI If you're curious, on XAMPP, session files are located in `/Applications/XAMPP/xamppfiles/temp`. You can open the session files within that directory to get a sense of how the data is encoded.

**Comment by maqboolk** [comment]
@susanBuck 
Thank you! I will try to experiment lil bit.
