### ISSUE TITLE
Comment shortcut in Visual Studio

### ISSUE THREAD

**Issue by britney-sandau** [susanBuck/e2-fall20#53]
Hi Professor,
 
Silly question here. What shortcut do you use in your videos to comment out multiple lines of code and add "//" for each line? I have tried to find out but my searches have failed me. I have found a way to use "/* comment */" but sometimes I would like to use your method.

Thank you for any feedback you can provide.

**Comment by CrimsonSIS** [comment]
Is this what you are referring to:

https://jeremybytes.blogspot.com/2015/12/visual-studio-shortcuts-comment.html

**Comment by susanBuck** [comment]
The command is called _**Toggle Line Coment**_

Keyboard shortcuts:

+ Mac: `CMD` + `/`
+ Windows: `CTRL` + `/`

Alternatively, it can be found under _Edit > Toggle Line Comment_.

(Thanks for asking this question! I try to cover all the keyboard shortcuts I use in the beginning of the semester when we go over VSCode, but I missed this one - will add it to the notes. : )

**Comment by britney-sandau** [comment]
Thank you so very much! These shortcuts have been most helpful.
