### ISSUE TITLE
outputting various results to index-view.php

### ISSUE THREAD

**Issue by britney-sandau** [susanBuck/e2-fall20#55]
I am not sure how to put this into words, but here it goes. I am building a guess my number game and was wondering if there is a way to display various results to my index-view.php page when you don't know what the result will be. The results are when the computer guesses the wrong number. Right now it will only display the last guess if I add an element in my index-view.php document. If I do a var_dump it shows all of the guesses that the computer made, so I know it is making various guesses, but I am unsure how to have a changing variable output to my page. 

For my first project I had to do some crazy formatting to get it to display onto the page by formatting in my index.php page, which is sloppy coding. So I was wondering if there is a way to format code when you do not know what the results will be. I have included a screenshot of how I want it to display. Again, it is working but only with the use of terrible coding practices.

I hope that makes sense. Thank you for any help in the right direction.

![Screen Shot 2020-10-13 at 7 55 03 PM](https://user-images.githubusercontent.com/57762932/95928470-6de2da00-0d8f-11eb-96bc-3c1abc467071.png)

**Comment by susanBuck** [comment]
Hi @britney-sandau -

On my initial read of this, it sounds like you should be accumulating results in an array, which you can then loop through in the view and display.

I think I need to see the code to better understand the game flow, though. Can you push your latest changes to Github?

**Comment by britney-sandau** [comment]
Thank you so much! I believe that is going to work.
