### ISSUE TITLE
FYI: php-cs-fixer plugin updated to v0.1.157 ("php general error" notification)

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall20#58]
Just a head's up that when working in VSCode you might start seeing this error popup when working in a PHP file:

![image](https://user-images.githubusercontent.com/237711/96052407-7d275d80-0e4b-11eb-8eca-8fe705a25045.png)

This happens because the php-cs-fixer plugin has updated from `v0.1.156` to `v0.1.157`, and if you've reloaded VSCode recently, it will automatically pull in this updated version.

Where this causes the problem is you'll recall in our settings we had a property for `php-cs-fixer.executablePath` that pointed to the path of the php-cs-fixer plugin which included the version number.

To address this, go back to your settings and update the so the version number in the path is `v0.1.157`.

![image](https://user-images.githubusercontent.com/237711/96052691-0fc7fc80-0e4c-11eb-98f2-dc815c1147e7.png)

Reference: https://hesweb.dev/e2/notes/misc/vscode-and-php#step-2-configure-settings

**Comment by alysonann** [comment]
@susanBuck Thank you! Just a note for those going to the reference--use "dev" instead of "loc":
[https://hesweb.dev/e2/notes/misc/vscode-and-php#step-2-configure-settings](https://hesweb.dev/e2/notes/misc/vscode-and-php#step-2-configure-settings).

**Comment by susanBuck** [comment]
Thanks for the catch @alysonann! Just updated the original link.
