### ISSUE TITLE
Question 5 - Troubleshooting Techniques - Opening error log file

### ISSUE THREAD

**Issue by trnason** [susanBuck/e2-fall20#6]
Hi Class,

Having trouble with question 5 on the Week 1 Assignment. I am using a MAC and it says the below:

**Find this information and then in your command line program navigate to the folder where your local server's Apache log file is.**

I found the pathway:
/Applications/XAMPP/xamppfiles/logs/error_log

When I use terminal, it says it cannot be found. Anyone know what I am doing wrong? 

![Screen Shot 2020-09-08 at 3 19 02 PM](https://user-images.githubusercontent.com/52473207/92524636-0d88d780-f1e8-11ea-9a1c-c3a53329648c.jpeg)

**Comment by susanBuck** [comment]
Hi @trnason -

It looks like the statement you are executing is `~cd//Applications/XAMPP/xamppfiles/logs/error_log`. 

There are two problems here:
1. The `cd` command is used to change directories; it is not used to view the contents of a file.
2. There's no space between the command (`cd`) and the path (`/Applications/XAMPP/xamppfiles/logs/error_log`)

Instead try something like this: `cat /Applications/XAMPP/xamppfiles/logs/error_log`

This uses the [cat](http://www.linfo.org/cat.html) command to show the contents of the file `/Applications/XAMPP/xamppfiles/logs/error_log`.

If that doesn't do the trick, let us know.

**Comment by susanBuck** [comment]
As a follow-up, in case you were trying to use `cd` (change directory) to move into the logs directory, you'd want to execute the following:

```bash
cd /Applications/XAMPP/xamppfiles/logs/
```

Then, once you're in that directory, you could open the `error_log` file with the cat command:

```bash
cat error_log
```

**Comment by trnason** [comment]
That solved it! Appreciate the quick help!
