### ISSUE TITLE
Fun read: Ninja code

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall20#64]
Hi everyone,

A couple lectures ago we talked about code style and design. On that topic, check out this "guide" to code style: https://javascript.info/ninja-code.

This guide is:
a) written in reference to JavaScript, but applicable to many different languages
b) purposefully humorous/tongue-in-cheek - basically you want to do the opposite of all the things it says. : )

**Comment by rlange2176** [comment]
"Try to shorten everything. Only a worthy person should be able to uphold the development of your code." Maybe what the creator behind strstr was going for? :) Funny read!

**Comment by CrimsonSIS** [comment]
A scream!

**Comment by britney-sandau** [comment]
This was a refreshing read! Thank you for sharing!
