### ISSUE TITLE
Notes Missing?

### ISSUE THREAD

**Issue by deleonl4** [susanBuck/e2-fall20#65]
Hi all,

I don't see two of the items on the left nav listed when trying to practice and follow along with class videos. Anyone experiencing the same issue?

Leslie
<img width="1440" alt="Screen Shot 2020-10-22 at 6 10 56 PM" src="https://user-images.githubusercontent.com/47702390/96935455-167cf200-1492-11eb-90b0-dc7da69ad402.png">

**Comment by deleonl4** [comment]
Just saw it under the next category...took me a minute to realize.

**Comment by susanBuck** [comment]
Sorry for the confusion - did a little bit of reorganizing!
