### ISSUE TITLE
Issue with XAMPP MySQL Database server?

### ISSUE THREAD

**Issue by mborjon** [susanBuck/e2-fall20#66]
Hello,

I set up week 8 per the normal process (added to virtual host and computer hosts), but I'm getting an error when I tried to access it via http://week8.loc (see attached pic).  I notice that on the XAMPP application manager, the MySQL Database is stopped (see attached pic).  I tried to restart it numerous times and it will not restart.  I have also attached my virtual host settings.

Does anyone have any ideas?

Thanks,
-Melinda
<img width="1021" alt="Screen Shot 2020-10-24 at 4 01 29 PM" src="https://user-images.githubusercontent.com/38201146/97095268-30ddd980-1612-11eb-86a3-3fbf5b18a470.png">
<img width="663" alt="Screen Shot 2020-10-24 at 3 54 00 PM" src="https://user-images.githubusercontent.com/38201146/97095269-320f0680-1612-11eb-90da-d6e9f9d2be4d.png">
<img width="583" alt="Screen Shot 2020-10-24 at 3 50 23 PM" src="https://user-images.githubusercontent.com/38201146/97095271-33d8ca00-1612-11eb-9316-2355b4c42a02.png">

**Comment by mborjon** [comment]
@susanBuck  Do you have any ideas? Thanks.

**Comment by susanBuck** [comment]
Don't worry about MySQL not starting right now - that shouldn't impact being able to access your site. The key thing is that Apache is started. 👍

Can you share the output of the troubleshooting command described here https://hesweb.dev/e2/notes/local-server/local-domains#troubleshooting ?

Also, can you share a copy/paste text version of your complete VirtualHosts file. I don't see any errors in the screenshot you shared, but I'd like to test the file on my end.

**Comment by mborjon** [comment]
Hello @susanBuck,

Here is the output from the command:
AH00112: Warning: DocumentRoot [/Applications/XAMPP/xamppfiles/docs/dummy-host.example.com] does not exist
AH00112: Warning: DocumentRoot [/Applications/XAMPP/xamppfiles/docs/dummy-host2.example.com] does not exist
AH00112: Warning: DocumentRoot [/Applications/XAMPP/xamppfiles/htdocs/e2/week8] does not exist
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server dummy-host.example.com (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:23)
         port 80 namevhost dummy-host.example.com (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:23)
                 alias www.dummy-host.example.com
         port 80 namevhost dummy-host2.example.com (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:32)
         port 80 namevhost practice.loc (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:40)
         port 80 namevhost e2p1.loc (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:50)
         port 80 namevhost e2p2.loc (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:60)
         port 80 namevhost week7.loc (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:70)
         port 80 namevhost practicep2.loc (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:80)
         port 80 namevhost week8.loc (/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf:90)
ServerRoot: "/Applications/XAMPP/xamppfiles"
Main DocumentRoot: "/Applications/XAMPP/xamppfiles/htdocs"
Main ErrorLog: "/Applications/XAMPP/xamppfiles/logs/error_log"
Mutex ssl-stapling: using_defaults
Mutex ldap-cache: using_defaults
Mutex proxy: using_defaults
Mutex ssl-cache: using_defaults
Mutex authn-socache: using_defaults
Mutex default: dir="/Applications/XAMPP/xamppfiles/logs/" mechanism=default 
Mutex mpm-accept: using_defaults
Mutex authdigest-opaque: using_defaults
Mutex proxy-balancer-shm: using_defaults
Mutex ssl-stapling-refresh: using_defaults
Mutex rewrite-map: using_defaults
Mutex authdigest-client: using_defaults
PidFile: "/Applications/XAMPP/xamppfiles/logs/httpd.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
Define: MODPERL2
User: name="daemon" id=1 not_used
Group: name="daemon" id=1 not_used

Also, here is the Virtual Host block:

<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot "/Applications/XAMPP/xamppfiles/docs/dummy-host.example.com"
    ServerName dummy-host.example.com
    ServerAlias www.dummy-host.example.com
    ErrorLog "logs/dummy-host.example.com-error_log"
    CustomLog "logs/dummy-host.example.com-access_log" common
</VirtualHost>

<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host2.example.com
    DocumentRoot "/Applications/XAMPP/xamppfiles/docs/dummy-host2.example.com"
    ServerName dummy-host2.example.com
    ErrorLog "logs/dummy-host2.example.com-error_log"
    CustomLog "logs/dummy-host2.example.com-access_log" common
</VirtualHost>

<VirtualHost *:80>
    ServerName practice.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/practice
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/practice>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName e2p1.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/p1
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/p1>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName e2p2.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/p2
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/p2>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName week7.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/week7
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/week7>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName practicep2.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/practice/p2
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/practice/p2>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName week8.loc
    DocumentRoot /Applications/XAMPP/xamppfiles/htdocs/e2/week8
    <Directory /Applications/XAMPP/xamppfiles/htdocs/e2/week8>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

**Comment by susanBuck** [comment]
Hi @mborjon -

Looking at the output of the command I asked you to run, it states:

> AH00112: Warning: DocumentRoot [/Applications/XAMPP/xamppfiles/htdocs/e2/week8] does not exist

Can you double check the status of your `week8` directory? Does it exist in `e2`? Does it contain a `index.php` file?

**Comment by mborjon** [comment]
Hi @susanBuck,

Yes, Week 8 is in e2 and it does contain a index.php file.

Thanks,
-M
<img width="1447" alt="Screen Shot 2020-10-26 at 6 24 51 PM" src="https://user-images.githubusercontent.com/38201146/97245695-da5ecf80-17b8-11eb-86a1-d496d4976f08.png">
<img width="254" alt="Screen Shot 2020-10-26 at 6 24 01 PM" src="https://user-images.githubusercontent.com/38201146/97245698-db8ffc80-17b8-11eb-8181-f0e21c3f2e8c.png">

**Comment by susanBuck** [comment]
Looks like it's `week 8` with a space - try renaming it to `week8` then restarting Apache.

**Comment by mborjon** [comment]
@susanBuck That worked!  Thank you.  My eyes did not catch that....

**Comment by susanBuck** [comment]
Glad it's all sorted out! : )
