### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by trnason** [susanBuck/e2-fall20#69]
Reviewing this: https://github.com/emmyzon/e2/tree/master/p2

**Are you able to produce any errors or unexpected results?** 
All worked as expected!
**Referencing the course notes on Form design flowLinks to an external site., describe the form design flow used in this project.**
Design C
**Are there any separation of concern issues (i.e. non-display specific logic in view files, display code in controller files)?** 
Nothing that I can see. All looks good!
**Are there aspects of the code that you feel were not self-evident and would benefit from comments?**
I didn't see any. This seems pretty straight forward and everything was formatted in a way that was easy to see and understand.
**List any/all built-in PHP methods used with a brief summary of what the method does.**
rand(min,max): Generates a random number between a  minimum and maximum that the programmer defines. 
header(): Sends a raw HTTP header
**Are there any parts of the code that you found interesting or taught you something new?**
The CSS and the image. Inspires me to add something like this on project 3! 
**Are there any parts of the code that you don't understand?**
No.
**Are there any best practices discussed in course material that you feel were not addressed in the code?**
Not that I could tell. 
**Are there any style inconsistencies in the code, or areas where the code style/design could be improved?**
Well styled and was consistent.
**Do you have any additional comments not covered in the above questions?**
Overall a great project. Well-written and organized in great way where it was pretty self-evident what the code was doing. This game is the same game that I made so it was cool to compare my code to this one and see any differences.

**Comment by trnason** [comment]
Whoops, wrong place

**Comment by deleonl4** [comment]
I love the fun colors and the gif used in this game, I actually played it and was entertained!
