### ISSUE TITLE
Composer Error wrt cache

### ISSUE THREAD

**Issue by mborjon** [susanBuck/e2-fall20#70]
Hello,

When downloading Composer,  I got an error regarding caching.  All seems to be working well.  How do I fix this and is it a concern?

Thanks,
-Melinda
<img width="822" alt="Screen Shot 2020-10-26 at 9 36 41 PM" src="https://user-images.githubusercontent.com/38201146/97342449-76351d80-1843-11eb-995e-699b55d1f496.png">

**Comment by susanBuck** [comment]
Hi @mborjon - it's not a critical problem. It means Composer is unable to write cache files. Composer should continue to function fine, it just won't be as optimized.

The following command should resolve that warning, as it will change ownership of your composer directory:

```
sudo chown -R $USER $HOME/.composer
```

(Note: This is specific to Mac users)

**Comment by mborjon** [comment]
@susanBuck thank you.
