### ISSUE TITLE
Issue with index.php in Rock Paper Scissors game

### ISSUE THREAD

**Issue by mborjon** [susanBuck/e2-fall20#74]
@susanBuck,

As I'm trying to set up and run the Rock Paper Scissors game, I'm getting the following error on my local server:
Parse error: syntax error, unexpected end of file in /Applications/XAMPP/xamppfiles/htdocs/e2/week8/index.php on line 88

Attached is a screenshot.  I'm a newbie to HTML.  What am I doing wrong? I went back to the notes from the form basics examples.

Thanks,
-Melinda

<img width="1025" alt="Screen Shot 2020-11-01 at 4 43 22 PM" src="https://user-images.githubusercontent.com/38201146/97820200-e556ab80-1c61-11eb-93b4-3e67992abb02.png">

**Comment by susanBuck** [comment]
Hi @mborjon -

It looks like the **if block on line 76** and **foreach block on line 78** are never closed.

Compare to my example for reference (I added comments to show what you're missing):

```html
<section id='recentGames'>
        <?php if ($recentGames): ?>
        <h2>Game history</h2>
        <?php foreach ($recentGames as $game): ?>
        <ul>
            <li>Player chose: <?= $game['player'] ?>
            <li>Computer chose: <?= $game['computer'] ?>
            <li>Outcome: <?= $game['outcome'] ?>
            <li>Played at: <?= $game['timestamp'] ?>
        </ul>
        <?php endforeach ?> <!-- You're missing this -->
        <?php endif ?> <!-- And this -->
    </section>
```

**Comment by mborjon** [comment]
@susanBuck Many thanks!
