### ISSUE TITLE
Getting an error when adding zipfoods.loc to my webserver 

### ISSUE THREAD

**Issue by pranjal-joshi97** [susanBuck/e2-fall20#75]
Hello, 
I'm getting the following error when I try to add zipfoods.loc to my webserver: 
![image](https://user-images.githubusercontent.com/42822597/97965995-cab13d80-1ded-11eb-8bd2-3555200d6b71.png)

I haven't gotten it before when uploading my p1 and p2. 

Any idea why this is happening? 

Thanks :)

**Comment by rlange2176** [comment]
Hi pranjal-joshi97,

Taking a guess here, but where are you in the process? Have you set up a virtual host block for this new app yet in the httpd-vhosts.conf file? https://hesweb.dev/e2/notes/local-server/local-domains

**Comment by susanBuck** [comment]
@pranjal-joshi97 -

Can you confirm you're opening the hosts file by prefixing the nano command with `elevate` ? e.g.:

```
elevate nano c:\Windows\System32\drivers\etc\hosts
```

This is necessary because the host file is admin protected.

Ref: https://hesweb.dev/e2/notes/local-server/local-domains#step-3-create-a-new-host

**Comment by pranjal-joshi97** [comment]
@rlange2176  yes I had set up the virtual host, but @susanBuck 's help worked! I keep forgetting the host file is admin protected 

 Thank you both :)

**Comment by susanBuck** [comment]
@pranjal-joshi97 Glad it's all sorted out!
