### ISSUE TITLE
Using chmod in terminal on cache file; "No such file or directory"

### ISSUE THREAD

**Issue by scoutperry** [susanBuck/e2-fall20#76]
Hi everyone,
Maybe I'm missing something, but after downloading the e2 framework I had issues changing the permissions on the cache file, terminal kept saying it couldn't find the directory.

```
e2 $ sudo chmod 777 cache
Password: #
chmod: cache: No such file or directory
```

I googled around and tried a command I found to get terminal to tell me the current set permissions
```
ls d@l cache
ls: d@l: No such file or directory
```
I could try to set permissions from the finder, but I was unsure if that was a good idea or not. 

Thanks!
-Scout

**Comment by susanBuck** [comment]
Hi @scoutperry -

It looks like you're running the command `sudo chmod 777 cache` from within your `e2` directory - you want to go one step further changing into the `zipfoods` directory and then run the command there.


Here's a screenshot showing me replicating the problem, then navigating into `zipfoods` and successfully running the command: 

![image](https://user-images.githubusercontent.com/237711/98050298-5e3f3a00-1dff-11eb-8589-e937ca2bdb02.png)

**Comment by scoutperry** [comment]
Annnd yep that works!
Thanks again,
-Scout
