### ISSUE TITLE
Getting error when running composer update for zipfoods

### ISSUE THREAD

**Issue by mborjon** [susanBuck/e2-fall20#77]
Hello @susanBuck 

When I run composer update, it says that I don't have a composer.json file, but I do.  Please advise.

Thanks,
-Melinda

<img width="574" alt="Screen Shot 2020-11-06 at 4 45 52 PM" src="https://user-images.githubusercontent.com/38201146/98426926-c4220080-204f-11eb-9888-d8a458103d65.png">
<img width="1309" alt="Screen Shot 2020-11-06 at 4 43 40 PM" src="https://user-images.githubusercontent.com/38201146/98426927-c5ebc400-204f-11eb-8818-82d8bc44a46c.png">

**Comment by susanBuck** [comment]
Hi @mborjon -

It looks like you're not in the zipfoods directory when you run `composer update`.

You want to first change into that directory using the `cd` (change directory) command:

```
cd /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods
```

Then run `composer update`. 

You can confirm you're in the correct directory by first running `ls` to view the contents of the directory. 

Also, note how the command line prompt always shows the path of the directory you're currently in. So if it just says `~` you're in your home directory. But if it says `/Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods` you know you're in the right spot.

![image](https://user-images.githubusercontent.com/237711/98427377-e5dcb100-206a-11eb-8cab-0c8c8ad214e9.png)

**Comment by mborjon** [comment]
@susanBuck Sorry, I thought I was.  Too many hours staring at results this week... Thank you!

**Comment by susanBuck** [comment]
@mborjon - no worries! I feel like my brain is still acclimating to the daylight savings time shift : )
