### ISSUE TITLE
Getting error after deploying zipfoods to the production server - The page showed IG4 

### ISSUE THREAD

**Issue by tatthung** [susanBuck/e2-fall20#78]
Dear Classmates, @susanBuck,

A little weird since the page showed only IG4 rather than Zipfoods content (after updating the fiiles to the production server). Any idea which step have I missed? Thank you.
![image](https://user-images.githubusercontent.com/10286253/98457409-e9cf1700-21c1-11eb-950e-6ebda7198087.png)

**Comment by tatthung** [comment]
Hi Guys, @susanBuck ,

I think i know what I have missed - did not add zipfoods on the CNAME record column under Advance DNS, my bad. I will close this post then. Thank you.

![image](https://user-images.githubusercontent.com/10286253/98457530-4c74e280-21c3-11eb-88af-935a0f99f070.png)

**Comment by susanBuck** [comment]
Glad you got to the bottom of it, @tatthung! :)
