### ISSUE TITLE
Issue deploying framework to production

### ISSUE THREAD

**Issue by deleonl4** [susanBuck/e2-fall20#79]
Hi all,

After following week 10, part2 instructions twice, and troubleshooting instructions, I am asking for help. I can't seem to figure out why my files aren't displaying on the server. On local everything works. I added as much context as possible below for troubleshooting help. Thank you!

<hr>

**URL:** http://myapp.lesliedeleon.xyz/
<img width="445" alt="Screen Shot 2020-11-08 at 10 37 02 AM" src="https://user-images.githubusercontent.com/47702390/98469965-9bfde300-21b0-11eb-9cb4-13b5fc0481c8.png">

<hr>

**VIRTUAL HOST CONFIG FILE:**
<img width="704" alt="Screen Shot 2020-11-08 at 10 49 57 AM" src="https://user-images.githubusercontent.com/47702390/98469886-30b41100-21b0-11eb-83e7-7b1ca1e113d9.png">

<hr>

**CHANGING PERMISSIONS & ENVIRONMENT FILE:**

<img width="583" alt="Screen Shot 2020-11-08 at 10 40 40 AM" src="https://user-images.githubusercontent.com/47702390/98469972-9f916a00-21b0-11eb-94b2-f3355750b606.png">

<hr>

<img width="706" alt="Screen Shot 2020-11-08 at 10 48 42 AM" src="https://user-images.githubusercontent.com/47702390/98469894-34e02e80-21b0-11eb-87b3-6893bcece6c8.png">

<hr>

**COMPOSER BUILDING VENDOR DIRECTORY WITHIN MyApp:**
<img width="1013" alt="Screen Shot 2020-11-08 at 10 47 48 AM" src="https://user-images.githubusercontent.com/47702390/98469975-a02a0080-21b0-11eb-90d3-ea13e75b0adb.png">

<hr>

**CODE FILE STRUCTURE:**
<img width="692" alt="Screen Shot 2020-11-08 at 10 36 18 AM" src="https://user-images.githubusercontent.com/47702390/98469961-93a5a800-21b0-11eb-920a-380744d72dfb.png">

**Comment by maqboolk** [comment]
@deleonl4 ,
I haven't watched the lecture 10 yet. 
Have you tried restarting your server ?

**Comment by deleonl4** [comment]
Yes, I forgot to add this screenshot. 


Best,
Leslie

**Comment by susanBuck** [comment]
Hi @deleonl4 - 

Because the url is resolving to the server, but not the subdomain specified by the Virtual Host, I believe we can narrow this down to a Virtual Host/server/domain config. I.e. not something related to the code/application setup.

On your production server can you run the command `apachectl -S` and share the output? This will report any syntax errors that may exist in your Virtual Host config file.

Also, can you copy/paste share the full contents of your Virtual Host config file here so I can replicate/test it exactly as is on my end?

**Comment by deleonl4** [comment]
@susanBuck, gotcha, I don't see any errors after running the command and the myapp.lesliedeleon.xyz showed up just fine as well.

<img width="867" alt="Screen Shot 2020-11-08 at 6 09 29 PM" src="https://user-images.githubusercontent.com/47702390/98486923-19941400-21ee-11eb-83c9-be6973e5a618.png">

                             
```                   
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

<Directory /var/www/html/>
Options Indexes FollowSymLinks
AllowOverride All
Require all granted
</Directory>

ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

<IfModule mod_dir.c>
            DirectoryIndex index.php index.pl index.cgi index.html index.xhtml index.htm
</IfModule>
</VirtualHost>

<VirtualHost *:80>
    ServerName practice.lesliedeleon.xyz
    DocumentRoot "/var/www/html/e2/practice"
    <Directory "/var/www/html/e2/practice">
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName e2p1.lesliedeleon.xyz
    DocumentRoot "/var/www/html/e2/p1"
    <Directory "/var/www/html/e2/p1">
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName e2p2.lesliedeleon.xyz
    DocumentRoot "/var/www/html/e2/p2"
    <Directory "/var/www/html/e2/p2">
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName e2week7.lesliedeleon.xyz
    DocumentRoot "/var/www/html/e2/week7"
    <Directory "/var/www/html/e2/week7">
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName e2week8.lesliedeleon.xyz
    DocumentRoot "/var/www/html/e2/week8"
    <Directory "/var/www/html/e2/week8">
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName myapp.lesliedeleon.xyz
    DocumentRoot /var/www/html/e2/MyApp/public
    <Directory /var/www/html/e2/MyApp/public>
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>
```

**Comment by susanBuck** [comment]
Oh weird - wonder what changed/fixed it? Glad it's working now!

**Comment by deleonl4** [comment]
Maybe it just needed a little extra time? Definitely weird! thank you!
