### ISSUE TITLE
Git download for Mac

### ISSUE THREAD

**Issue by scoutperry** [susanBuck/e2-fall20#8]
Hi!

I noticed that there are multiple ways to download Git for Mac OS, and I was wondering if anyone had any insight on the differences between the different ways to download it.

Thanks,
-Scout

**Comment by susanBuck** [comment]
Hi @scoutperry - Good question.

https://git-scm.com/download/mac lists 4 ways to get Git:

1. via [Homebrew](https://brew.sh/), which is a command line package/program for managing software on a Macs.
2. via Xcode (a Mac OS development environment)
3. via a binary installer - This is a compiled version of git, ready to run on your computer.
4. via source - This is the uncompiled version of git, allowing you to see the actual source code of git; if you want to run it from this download, you'd have to first compile it. 

If you were looking to do the most straightforward download/install, you'd go with #3.

**Comment by scoutperry** [comment]
Thank you!
