### ISSUE TITLE
Theme not working on Zipfoods files

### ISSUE THREAD

**Issue by mborjon** [susanBuck/e2-fall20#80]
Hello @susanBuck,

I find it very useful if my theme matches yours as I am working along with your videos.  For some reason, the theme is not working on the Zipfoods files this week. Can you advise? (I'm attaching a screenshot of my vscode screen, the extension details that says it's enabled, and your screen for the same file from the video).

Thanks,
-Melinda

<img width="471" alt="Screen Shot 2020-11-08 at 4 54 28 PM" src="https://user-images.githubusercontent.com/38201146/98489987-016bc700-21e5-11eb-98b8-eb751cf2c5ef.png">
<img width="842" alt="Screen Shot 2020-11-08 at 5 05 23 PM" src="https://user-images.githubusercontent.com/38201146/98489997-07fa3e80-21e5-11eb-918b-de795bc5737d.png">
<img width="938" alt="Screen Shot 2020-11-08 at 4 54 41 PM" src="https://user-images.githubusercontent.com/38201146/98490054-34ae5600-21e5-11eb-9d07-83076cc39326.png">

**Comment by susanBuck** [comment]
@mborjon - I have an VSCode extension installed called "Laravel Blade" (by *amirmarmul*) that adds syntax highlighting for Blade files (`.blade.php`)

Thanks for bringing this up - I should have mentioned it when we started working with Blade files!

**Comment by mborjon** [comment]
Got it and works. Thanks!
