### ISSUE TITLE
Routes not working on server (404 error)

### ISSUE THREAD

**Issue by deleonl4** [susanBuck/e2-fall20#81]
Hi Eveyone,

I'm having an issue seeing my routes on the server. I went over the notes on "[Prep Digital Ocean](https://hesweb.dev/e2/notes/php/frameworks/deploy)" again to troubleshoot but it still isn't working. They work fine on local. I copied Susan's file to see if that would work and I still get the 404. Any ideas what it could be?

<img width="828" alt="Screen Shot 2020-11-09 at 8 38 29 AM" src="https://user-images.githubusercontent.com/47702390/98548065-125d1c80-2267-11eb-8a12-a12c9c6dc540.png">

**Comment by susanBuck** [comment]
This would happen if the modrewrite module is not enabled on your server. This module is necessary for routing to work.

Double check the steps described here: https://hesweb.dev/e2/notes/php/frameworks/deploy#prep-digialocean

If modrewrite *is* enabled, the command `sudo a2enmod rewrite` should output something like this:

```
root@e2:/var/www/html/e2# sudo a2enmod rewrite
Module rewrite already enabled
```

**Comment by deleonl4** [comment]
They worked after I set up the right Controller files for each. Thank you!
