### ISSUE TITLE
myapp.loc/products pointing to error on provided imported file

### ISSUE THREAD

**Issue by deleonl4** [susanBuck/e2-fall20#82]
Hi all, I can't see the ProductController.php file's index function output. It points to an error on one of the files that Susan provided us, anyone facing the same issue?

<hr>

**BROWSER VIEW:**

<img width="1324" alt="Screen Shot 2020-11-09 at 9 24 59 AM" src="https://user-images.githubusercontent.com/47702390/98554034-42f48480-226e-11eb-9573-071869712827.png">

<hr>

**CODE:**

<img width="1293" alt="Screen Shot 2020-11-09 at 9 31 00 AM" src="https://user-images.githubusercontent.com/47702390/98554153-66b7ca80-226e-11eb-9528-b176d5f32daf.png">

**Comment by deleonl4** [comment]
When troubleshooting further, I went into the AppController.php file to find that I needed to update the index function to the code used within the video (week 10, part 3) but when doing this the main page myapp.loc now returns this:

**BROWSER: VIEW:**
<img width="1316" alt="Screen Shot 2020-11-09 at 9 40 30 AM" src="https://user-images.githubusercontent.com/47702390/98555629-28bba600-2270-11eb-9eb0-416d612290df.png">

<hr>

**CODE:**
<img width="1294" alt="Screen Shot 2020-11-09 at 9 42 52 AM" src="https://user-images.githubusercontent.com/47702390/98555622-26594c00-2270-11eb-9e13-cb7a750ff5e2.png">

**Comment by susanBuck** [comment]
Hi @deleonl4 -

I think you need to revisit the [Week 9 Part 6 video](https://www.youtube.com/embed/eeYe8GxobaM?rel=0&showinfo=0) starting at the 10:07 mark where I cover the creation of a ProductController.

The first error you shared is noting that it can't find a `ProductController` class, and from your screenshots I can see in the file browser that it does not exist.

RE:
> I went into the AppController.php file to find that I needed to update the index function to the code used within the video (week 10, part 3)

You don't want to edit the `index` method within `AppController`. You need to create a `ProductController` and have an index method within there.

Note how the routes are set up such that urls like `/products` and `/product` should be pointing to a `ProductController`:
```
return [
    # Ex: The path `/` will trigger the `index` method within the `AppController`
    '/' => ['AppController', 'index'],
    '/contact' => ['AppController', 'contact'],
    '/about' => ['AppController', 'about'],
    '/products' => ['ProductController', 'index'],
    '/product' => ['ProductController', 'show'],
];
```

Also, if needed for reference, here's the [ProductController.php in my ZipFoods](https://github.com/susanBuck/e2/blob/master/zipfoods/app/Controllers/ProductController.php).

Let me know if you need any follow-up assistance after you set up this controller.

**Comment by deleonl4** [comment]
@susanBuck, that's my fault for missing that part, and again on week 10 part 3...maybe, I started too early this morning. I understand how the file structures work now after going over the video, thank you so much.

**Comment by susanBuck** [comment]
No problem - it's a lot to keep track of at first!
