### ISSUE TITLE
Clarification on Q1 on WK 10 Homework

### ISSUE THREAD

**Issue by pllealfunes** [susanBuck/e2-fall20#83]
Hi @susanBuck, I'm looking over week 10 homework and wanted to know if Q1 is optional or if it needs to be submitted. I've attached screenshots showing that it says it's optional but still worth 16 points. 

Thanks.

<img width="739" alt="Screen Shot 2020-11-09 at 2 52 07 PM" src="https://user-images.githubusercontent.com/51715816/98590450-d6dd4500-229c-11eb-9c1e-bceb29aa5b6c.png">
<img width="731" alt="Screen Shot 2020-11-09 at 2 52 21 PM" src="https://user-images.githubusercontent.com/51715816/98590469-dcd32600-229c-11eb-8df2-03aa732c2c8a.png">

**Comment by susanBuck** [comment]
Hi @pllealfunes -

That question should not have an open-ended input - it should have a single checkbox that says *I have completed this exercise.*.

I've just re-saved the assignment in Canvas to try and update it, but you will continue to see the old version unless you restart the assignment. No need to do that though, you can just write "I have completed this exercise." in the box. : )

**Comment by pllealfunes** [comment]
Great! Thank you so much for the clarification.
