### ISSUE TITLE
Blade formatter/fixer?

### ISSUE THREAD

**Issue by alysonann** [susanBuck/e2-fall20#85]
Thank you for this. Do you also have a specific Blade formatter/fixer (for indentations and line spacing)? I've tried to few extensions and nothing seems to make a difference.

Editing here... I think I was just noticing that the beginning of line spacing/indentation is different in the videos. I was trying to get VSCode to recreate that, but wasn't noticing that instead of creating spacing it was taking it away, making it look more like the Notes. If the formatting in the Notes is fine, then I think I'm all set.

------------------------------------------------------------------------------
@mborjon - I have an VSCode extension installed called "Laravel Blade" (by *amirmarmul*) that adds syntax highlighting for Blade files (`.blade.php`)

Thanks for bringing this up - I should have mentioned it when we started working with Blade files!

_Originally posted by @susanBuck in https://github.com/susanBuck/e2-fall20/issues/80#issuecomment-723716171_

**Comment by rlange2176** [comment]
Thank you for this! Was having this issue as well. An extra space was getting added before the ['id'] on line 3 below, which was breaking the individual product pages. 
```html
<div id='product-index'>
    @foreach($products as $product)
    <a href='/product?id={{ $product['id'] }}'>
        <div class='product'>
            <div class='product-name'>{{ $product['name'] }}</div>
            <img class='product-thumb' src="/images/products/{{ $product['id'] }}.jpg">
        </div>
    </a>
    @endforeach
</div>
```

**Comment by susanBuck** [comment]
@alysonann -

I'm reviewing the [Week 10, Part 3](https://www.youtube.com/embed/VYtgJrlBgB8?rel=0&showinfo=0) video and notice that at the end of the video as I'm wrapping up the "All products" view the code looks like this:

![image](https://user-images.githubusercontent.com/237711/98959596-6e2ade00-24d1-11eb-89ba-6f5df22a9a61.png)

I think at this point, though, I hadn't saved the file and the auto-formatter had not run yet. Given this, there are two pending issues the auto-formatter will clean up:

1. The `@foreach..@endforeach` should be indented within the `<div id='product-index'>...</div>`
2. The `<div class='product'>...</div>` should be indented within the `<a href='/product?id={{ $product["id"] }}'>..</a>`

Once the formatter has run, though, it looks like this (this is a screenshot from my file as it looks right now in VSCode):

![image](https://user-images.githubusercontent.com/237711/98959824-acc09880-24d1-11eb-9ec1-29071fecaf30.png)

And that matches up with what we see in the notes:

![image](https://user-images.githubusercontent.com/237711/98959864-b944f100-24d1-11eb-9ff3-df9d76d1c1ea.png).

Note, however, that none of this formatting is done via a Blade-specific formatter - it's all just the default HTML editor. There are Blade-specific formatters how there, but I don't currently have any of them installed. 

Let me know if this clears things up, or if there are still discrepancies you're unsure about/I'm missing. : )

**Comment by susanBuck** [comment]
@rlange2176 - That's odd/frustrating! 

Via command line, can you navigate to your extensions directory (`cd c:\Users\YourUsername\.vscode\extensions\`) and list the contents (`ls`) then share the output here?

Also, share the contents of your settings (`cat %HOME%\AppData\Roaming\Code\User\settings.json`).

**Comment by alysonann** [comment]
@susanBuck Thanks, this helps! I think I was mainly wondering about things like that @section at the top. My code editor is leaving everything flush at the left, like in the notes

![Screen Shot 2020-11-12 at 4 57 06 PM](https://user-images.githubusercontent.com/31620333/99000997-1fe50180-2508-11eb-8970-dc50528d4420.png)
![Screen Shot 2020-11-12 at 4 58 30 PM](https://user-images.githubusercontent.com/31620333/99001125-53279080-2508-11eb-8a1d-f4485e3a9ef1.png)

but sometimes I was seeing spacing below, like at the very top of your first (unsaved/auto-corrected) screenshot. Some indenting seemed logical to me, so I kind of wanted my editor to do it rather than take it away! But I won't worry about it.

**Comment by susanBuck** [comment]
@alysonann - I see what you mean, and agree it seems logical that the contents of our Blade directives would/should be indented. 

Like you did, I tried a bunch of different plugins now and can't find one that actually does this. :-(

This one, [shufo/vscode-blade-formatter](https://github.com/shufo/vscode-blade-formatter) even shows the indentation in the demo/screenshot, but when I install it, it does nothing.

[Here's a long thread on it where people mention all sorts of different solutions, with varying reports of non-success in comments...](https://stackoverflow.com/questions/46268211/how-to-format-laravel-blade-codes-in-visual-studio-code)

All this research is refreshing my memory that I've been down this path before - I kind of remember disabling auto-formatting in my .blade.php files out of frustration so I could use the indentation I wanted. That would explain why in the Week 10, Part 3 video we're referencing (which was recorded last semester), we see the expected indentation.

But then I think I got frustrated that my HTML code wasn't auto-formatted, so I re-enabled formatting at some point and just accepted that my blade directives weren't indenting as I wanted. 

I'll keep poking at this and if I come up with some winning combination of settings/extensions, I'll definitely let you know. : )

**Comment by rlange2176** [comment]
Hi @susanBuck - here are my extensions and json settings.

![image](https://user-images.githubusercontent.com/30083707/99608007-0eee3180-29db-11eb-9e8c-781c9bed840b.png)

**Comment by susanBuck** [comment]
@rlange2176 - Nothing unique stands out in your settings/extensions.

Are you still experiencing this problem?

> An extra space was getting added before the ['id']

**Comment by rlange2176** [comment]
No, not having the issue anymore since installing the Laravel Blade extension. Sorry if that wasn't clear earlier. Thanks!
