### ISSUE TITLE
Deploy to Production - Stuck on step 1

### ISSUE THREAD

**Issue by trnason** [susanBuck/e2-fall20#86]
Hi Class,

I seem to be stuck at step one when I need to download mbstring using this command (apt install php7.4-mbstring) and get the below error message. Any help would be most appreciated. 

<img width="839" alt="Screen Shot 2020-11-11 at 8 11 56 PM" src="https://user-images.githubusercontent.com/52473207/98886694-2ae15880-245a-11eb-8db0-d79513e09ffe.png">

**Comment by susanBuck** [comment]
Hi @trnason - Are you SSH'd into your DigitalOcean server when running this command?

**Comment by trnason** [comment]
Yes! That was the issue. My goodness, I can't believe I missed that.

Thank you as always!
