### ISSUE TITLE
$app->config('app.url') in the 404 file

### ISSUE THREAD

**Issue by alysonann** [susanBuck/e2-fall20#87]
I need to do a bit more digging, but I'm confused about what is going on in the 404 view as-is.
`<a href='{{ $app->config('app.url') }}'>{{ $app->config('app.url') }}</a>`

On my local server, in the html it says it will go back to `http://zipfoods.loc` but I took a screenshot while hovering over the link, so you can see that it links to what is in the address bar (so the link to the null value). Just confused about what is really going on. Thanks!
<img width="619" alt="Screen Shot 2020-11-12 at 1 33 44 PM" src="https://user-images.githubusercontent.com/31620333/98981247-b48d3680-24eb-11eb-84f2-911eb4d3ba50.png">

**Comment by susanBuck** [comment]
Interesting - in my tests (on Chrome and Firefox) it has the link going to http://zipfoods.loc.

Can you right click in the browser window and find the option to "View Source" and share the rendered HTML code?

For example, on my end it looks like this:

```html
<!doctype html>
<html lang='en'>
<head>

	<title>404 Page Not Found</title>
	<meta charset='utf-8'>

</head>
<body>

<h2>404 Page Not Found</h2>
<a href='http://zipfoods.loc'>http://zipfoods.loc</a>
	
</body>
</html>
```

Can you also share the contents of the `.env` file within the project? (That's where the app URL that is being used for this link is set)

**Comment by alysonann** [comment]
Thanks! The source shows `http://zipfoods.loc`.
```html
<!doctype html>
<html lang='en'>

<head>

    <title>404 Page Not Found</title>
    <meta charset='utf-8'>
</head>

<body>

    <h2>404 Page Not Found</h2>
    <a href=''>http://zipfoods.loc</a>

</body>

</html>
```

This is my current .env file. 
```
APP_NAME='ZipFoods Local'
APP_URL='http://zipfoods.loc'

DB_HOST='127.0.0.1'
DB_NAME='myapp'
DB_USERNAME='root'
DB_PASSWORD=''
```

**Comment by susanBuck** [comment]
How odd:

```html
<a href=''>http://zipfoods.loc</a>
```

As you noted, that line is created from this code in 404.blade.php:

```html
<a href='{{ $app->config('app.url') }}'>{{ $app->config('app.url') }}</a>
```

Note we're just using the same value twice `$app->config('app.url')` ...so why does it work in the second instance (the link label), but not the first instance (the link href)?

Can you push all your recent changes to your github repo so I can clone on my end and test your code base exactly as you have it?

**Comment by alysonann** [comment]
Apologies for the delay: http://zipfoods.alysonann.xyz/

I think I figured it out! The problem was in my `404.blade.php`. I had an extra space before app.url, and I didn't notice that there wasn't actually a link in the quotes in my href tag in View Source above: 

  `  <a href='{{ $app->config(' app.url') }}'>{{ $app->config('app.url') }}</a>`
instead of 
`    <a href='{{ $app->config('app.url') }}'>{{ $app->config('app.url') }}</a>`

And thus 
` <a href=''>http://zipfoods.loc</a>`
instead of 
`<a href='http://zipfoods.loc'>http://zipfoods.loc</a>`

Of course I copied the code I first posted from https://github.com/susanBuck/e2/blob/master/zipfoods/views/errors/404.blade.php rather than from my local file, because I had gone there to check it against mine (but didn't notice the space). "smh/facepalm emoji" I won't do that again...

Sorry about that! Thanks for your help!
