### ISSUE TITLE
GIT Configuration issue

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2-fall20#9]
Hi! I'm having the following issue. What to do?

:-)

![2020_09_11_GIT_Config_Errors](https://user-images.githubusercontent.com/53196073/92954366-5384ac00-f431-11ea-9906-c416623d69ea.png)

**Comment by susanBuck** [comment]
Hi @crimsonsis! Can you share the contents of the file `/users/cole/.gitconfig` so we can track down the error it's referring to?

**Comment by susanBuck** [comment]
Also, for reference, below is what my `.gitconfig` file looks like (yours does not have to exactly look like mine, but it gives you an idea of the basic syntax of this file which may help you track down the error):

```
[user]
[core]
	quotepath = false
	excludesfile = /Users/Susan/.gitignore
	filemode = false
	editor = /usr/bin/nano
	autocrlf = input
[difftool "sourcetree"]
	cmd = opendiff \"$LOCAL\" \"$REMOTE\"
	path = 
[mergetool "sourcetree"]
	cmd = /Applications/SourceTree.app/Contents/Resources/opendiff-w.sh \"$LOCAL\" \"$REMOTE\" -ancestor \"$BASE\" -merge \"$MERGED\"
	trustExitCode = true
[color]
	ui = true
	
[alias]
	lg = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative

[filter "media"]
	clean = git-media-clean %f
	smudge = git-media-smudge %f
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[user]
	name = Susan Buck
	email = susan@susanbuck.net
```

**Comment by tatthung** [comment]
Hi @CrimsonSIS, 

I wonder if this might work for you:  

`nano ~/.gitconfig`


and check if you have something like this (if not, maybe you might want to manually edit your codes by including something like this to the file - remember to save the file:

```
[core]
	autocrlf = input
        filemode = false
        editor = nano

[user]
	name = Tatt Hung
        email = tlhung@hotmail.com

[color]
	ui = true
```

**Comment by CrimsonSIS** [comment]
> Hi @CrimsonSIS! Can you share the contents of the file `/users/cole/.gitconfig` so we can track down the error it's referring to?

![2020_09_13_gitconfig](https://user-images.githubusercontent.com/53196073/93026034-f0ca1680-f5d0-11ea-984b-2585041730bd.png)

**Comment by CrimsonSIS** [comment]
I'll try uncommenting...

:-)

**Comment by susanBuck** [comment]
Line 2 looks problematic to me - it's as if the `[user]` code got mixed in with a comment.

It should look more like this:

```
[user]
	name = Jerald Dana Cole
        email = jerald_cole@alumni.harvard.edu
```

**Comment by CrimsonSIS** [comment]
Resolved! It is working beautifully! 

:-)
