### ISSUE TITLE
minLength:200 is not working

### ISSUE THREAD

**Issue by tatthung** [susanBuck/e2-fall20#90]
Dear All, @susanBuck,

I copied the validate code from the website, but the website failed showing the proper error message "The value for review must be at least 200 characters long". What could possibly be my issue? Thank you.

Validate code on show.blade.php
```
@if($app->errorsExist())
<ul class='error alert alert-danger'>
    @foreach($app->errors() as $error)
    <li>{{ $error }}</li>
    @endforeach
</ul>
@endif
```

Validate code on ProductController
```
public function saveReview()
     {
        $this->app->validate([
        'name' => 'required',
        'review' => 'required|minLength=200', # Note how multiple validation rules are separated by a |
        ]);

        $name = $this->app->input('name');
        $review = $this->app->input('review');
        $id = $this->app->input('id');
        
        #Persist the review to the database

        $this->app->redirect('/product?id='.$id, ['name' => $name]);

     }
```

![image](https://user-images.githubusercontent.com/10286253/99098935-b0106d00-2614-11eb-9947-081175535f25.png)

**Comment by susanBuck** [comment]
Hi @tatthung -

Try changing `minLength=200` to `minLength:200`. 

Let me know if that doesn't fix it. : )

**Comment by tatthung** [comment]
Dear @susanBuck ,

It still showed the same error message "The value for review can not be blank".

**Comment by susanBuck** [comment]
@tatthung - Could you push all your latest code changes to github so I can clone your repo locally to debug on my end?

**Comment by tatthung** [comment]
@susanBuck, it was my mistake, i have not changed the label name and id from `content` to `review` on show.blade.php, this is why both the controller and show.blade.php are not linked properly - It is working well now, thank you!
