### ISSUE TITLE
Issue with Review field and Minimum Character 

### ISSUE THREAD

**Issue by mborjon** [susanBuck/e2-fall20#91]
Hello @susanBuck,

I'm getting the expected results when I enter under 200 characters in my review field here:

<img width="1183" alt="Screen Shot 2020-11-15 at 6 23 43 PM" src="https://user-images.githubusercontent.com/38201146/99206382-1958c300-2770-11eb-8264-28b5165647b3.png">

But, when I enter 200 or more characters, I get fatal errors:

<img width="1185" alt="Screen Shot 2020-11-15 at 6 29 48 PM" src="https://user-images.githubusercontent.com/38201146/99206584-971cce80-2770-11eb-8a6e-6cec0f875e39.png">

<img width="1184" alt="Screen Shot 2020-11-15 at 6 23 03 PM" src="https://user-images.githubusercontent.com/38201146/99206418-342b3780-2770-11eb-9638-55c4cff0a4de.png">

Here are my VSCode pages:

<img width="983" alt="Screen Shot 2020-11-15 at 6 28 16 PM" src="https://user-images.githubusercontent.com/38201146/99206476-5755e700-2770-11eb-830f-6f5820b4f80f.png">

<img width="965" alt="Screen Shot 2020-11-15 at 6 28 40 PM" src="https://user-images.githubusercontent.com/38201146/99206501-65a40300-2770-11eb-914c-494f0dd3b172.png">

Please advise.

Thank you!
-Melinda

**Comment by susanBuck** [comment]
Hi @mborjon -

The error notes **View [example] not found**.

Looking in your ProductController on line 55 we see it's attempting to return a view called `example`, which probably does not exist. I don't think you need that line there.

For reference, here's what my [`saveReview` method looks like in ProductController](https://github.com/susanBuck/e2/blob/master/zipfoods/app/Controllers/ProductController.php#L57):

```php
public function saveReview()
    {
        $this->app->validate([
            'name' => 'required',
            'content' => 'required|minLength:200',
        ]);

        # If the above validation fails, the user is redirected back to the product page
        # and none of the following code will execute
        
        # Extract data from the form submission
        $name = $this->app->input('name');
        $content = $this->app->input('content');
        $id = $this->app->input('id');
        
        # TODO: Persist the review to the database

        # Send the user back to the product page with a `confirmationName`
        # we'll use to display a confirmation message.
        $this->app->redirect('/product?id='.$id, ['confirmationName' => $name]);
    }
```

**Comment by mborjon** [comment]
Thanks!  That fixed it.
