### ISSUE TITLE
Copy zipfoods to zipfoods2

### ISSUE THREAD

**Issue by maqboolk** [susanBuck/e2-fall20#95]
@susanBuck 
Hi Susan,

I would like to know if there are any steps I need to follow to copy zipfoods to zipfoods2.

If I copy whole folder and makes changes to env file with new project name, will it work?

**Comment by tatthung** [comment]
hi @maqboolk, i tried but did not work, so i created everything from scratch.

**Comment by susanBuck** [comment]
Hi @maqboolk -

You can copy a project, yes. After copying, you just want to remove and rebuild the _vendor_ directory so any of the composer configs will be re-written relevant to the new directory.

To do this, remove the vendor directory in the new project:

```bash
rm -rf vendor
```

And then rebuild it by invoking Composer:

```bash
composer install
```

Also, if you're on a Mac, [you would need to adjust the permissions](https://hesweb.dev/e2/notes/php/frameworks/setup#permissions) just like you did when setting up a new app.

All of this being said, though, I do *not* suggest copying ZipFoods if your intention is to use the copy as a base for Project 3. It's important to iterate through the full application process build for practice and to solidify the concepts we've been studying.

**Comment by maqboolk** [comment]
@susanBuck,

Thank you! I will try that. 

@susanBuck 
I just saw that you mentioned not  to copy the zipfoods for p3. I started p3 from scratch.

this is for myself, I want to keep weekly progress in different project. (Zipfoods, zipfoodsweek11, and zipfoodsweek12.
Zipfoods at the end of week 12 does not have all the details about connection using json file.

**Comment by maqboolk** [comment]
> hi @maqboolk, i tried but did not work, so i created everything from scratch.

@tatthung , Thanks!

**Comment by maqboolk** [comment]
> ```shell
> rm -rf vendor
> ```
